In [1]:
import duckdb
from functions.evaluation import evaluate
from networks.cnn_tiny import CNNModel
from networks.cnn_network import build_dataloaders


con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


train_rows = df[df['set'] == 'train']
val_rows   = df[df['set'] == 'val']
test_rows  = df[df['set'] == 'test']

drop_indices = train_rows[train_rows['label'] == 0].sample(frac=0.7).index

train_rows = train_rows.drop(drop_indices)
train_rows = train_rows[train_rows['label'].isin([0,1])]
val_rows = val_rows[val_rows['label'].isin([0,1])]

print(f"Antal utan m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 0])}")
print(f"Antal med m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 1])}")

CNN = CNNModel()
cnn_train_dl, cnn_val_dl, _ = build_dataloaders(train_rows, val_rows, val_rows)
CNN.reset_weights()
CNN.retrain(cnn_train_dl,cnn_val_dl,patience=15)

con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


k_fold_rows = df[df['set'].isin(['train','val']) ].copy()
k_fold_rows = k_fold_rows[k_fold_rows['label'].isin([0,1])]
drop_indices = k_fold_rows[k_fold_rows['label'] == 0].sample(frac=0.7).index
k_fold_rows = k_fold_rows.drop(drop_indices)
print(f"Totalt antal utan m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 0])}")
print(f"Totalt antal med m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 1])}")

test_rows  = df[df['set'] == 'test']


CNN = CNNModel()
CNN.retrain_with_k_fold(k_fold_rows)

Antal utan m-komponent i träningsdatan: 17903
Antal med m-komponent i träningsdatan: 2553
Total parameters: 15,710
  -> ny bästa modell sparad till ../models/cnn_tiny.pth
Epoch   0 | train: 0.8461 | val: 0.3946 | acc: 92.39% | AUC: 0.920  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny.pth
Epoch   1 | train: 0.4463 | val: 0.2795 | acc: 95.83% | AUC: 0.963  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny.pth
Epoch   2 | train: 0.3421 | val: 0.2490 | acc: 94.92% | AUC: 0.978  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny.pth
Epoch   3 | train: 0.2884 | val: 0.1592 | acc: 98.14% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny.pth
Epoch   4 | train: 0.2460 | val: 0.1350 | acc: 98.11% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny.pth
Epoch   5 | train: 0.2248 | val: 0.1727 | acc: 96.71% | AUC: 0.994  | LR: 0.001
Epoch   6 | train: 0.1989 | val: 0.1573 | acc: 96.93% | AUC: 0.994  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny.pth
Epoch   7 | train: 0.1903 | val: 0.1512 | acc: 97.17% | AUC: 0.994  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny.pth
Epoch   8 | train: 0.1828 | val: 0.1480 | acc: 97.23% | AUC: 0.994  | LR: 0.001
Epoch   9 | train: 0.1800 | val: 0.1656 | acc: 96.62% | AUC: 0.994  | LR: 0.001
Epoch  10 | train: 0.1635 | val: 0.1169 | acc: 98.05% | AUC: 0.994  | LR: 0.001
Epoch  11 | train: 0.1531 | val: 0.1090 | acc: 98.24% | AUC: 0.994  | LR: 0.001
Epoch  12 | train: 0.1516 | val: 0.1037 | acc: 98.39% | AUC: 0.994  | LR: 0.001
Epoch  13 | train: 0.1452 | val: 0.1098 | acc: 98.17% | AUC: 0.994  | LR: 0.001
Epoch  14 | train: 0.1434 | val: 0.1058 | acc: 98.11% | AUC: 0.993  | LR: 0.001
Epoch  15 | train: 0.1394 | val: 0.1345 | acc: 97.26% | AUC: 0.993  | LR: 0.001
Epoch  16 | train: 0.1395 | val: 0.0994 | acc: 98.57% | AUC: 0.992  | LR: 0.001
Epoch  17 | train: 0.1378 | val: 0.1163 | acc: 97.72% | AUC: 0.992  | LR: 0.001
Epoch  18 | train: 0.1386 | val: 0.1172 | acc: 97.51% | AUC: 0.994  | LR: 0.001
Epoch  19 | train: 0.1260 | val: 0.1299 | acc: 97.05% | AUC: 0.994  | LR: 0.001
Epoch  20 | train: 0.1263 | val: 0.1039 | acc: 97.93% | AUC: 0.993  | LR: 0.001
Epoch  21 | train: 0.1286 | val: 0.1122 | acc: 97.78% | AUC: 0.993  | LR: 0.001
Epoch  22 | train: 0.1224 | val: 0.0959 | acc: 98.45% | AUC: 0.993  | LR: 0.001
Epoch  23 | train: 0.1161 | val: 0.1324 | acc: 96.78% | AUC: 0.993  | LR: 0.001
Epoch  24 | train: 0.1102 | val: 0.1026 | acc: 98.14% | AUC: 0.992  | LR: 0.001
Epoch  25 | train: 0.1223 | val: 0.1275 | acc: 96.74% | AUC: 0.994  | LR: 0.001
Epoch  26 | train: 0.1143 | val: 0.1051 | acc: 97.90% | AUC: 0.993  | LR: 0.001
Epoch  27 | train: 0.1016 | val: 0.1257 | acc: 96.78% | AUC: 0.993  | LR: 0.001
Epoch  28 | train: 0.1042 | val: 0.1083 | acc: 97.60% | AUC: 0.993  | LR: 0.001
Epoch  29 | train: 0.1034 | val: 0.1614 | acc: 95.07% | AUC: 0.994  | LR: 0.001
Epoch  30 | train: 0.1046 | val: 0.0957 | acc: 98.33% | AUC: 0.993  | LR: 0.001
Epoch  31 | train: 0.1101 | val: 0.1018 | acc: 97.72% | AUC: 0.994  | LR: 0.001
Epoch  32 | train: 0.1053 | val: 0.1785 | acc: 94.31% | AUC: 0.993  | LR: 0.0005
Epoch  33 | train: 0.0932 | val: 0.1393 | acc: 96.14% | AUC: 0.993  | LR: 0.0005
Epoch  34 | train: 0.0897 | val: 0.1486 | acc: 95.53% | AUC: 0.994  | LR: 0.0005
Epoch  35 | train: 0.0926 | val: 0.1138 | acc: 97.02% | AUC: 0.992  | LR: 0.0005
Epoch  36 | train: 0.0861 | val: 0.1203 | acc: 96.71% | AUC: 0.993  | LR: 0.0005
Epoch  37 | train: 0.0862 | val: 0.1046 | acc: 97.63% | AUC: 0.993  | LR: 0.0005
Epoch  38 | train: 0.0822 | val: 0.1399 | acc: 95.74% | AUC: 0.993  | LR: 0.0005
Epoch  39 | train: 0.0843 | val: 0.1087 | acc: 97.26% | AUC: 0.992  | LR: 0.0005
Epoch  40 | train: 0.0841 | val: 0.1114 | acc: 97.23% | AUC: 0.993  | LR: 0.0005
Epoch  41 | train: 0.0862 | val: 0.1052 | acc: 97.54% | AUC: 0.992  | LR: 0.0005
Epoch  42 | train: 0.0868 | val: 0.1015 | acc: 97.84% | AUC: 0.992  | LR: 0.0005
Epoch  43 | train: 0.0796 | val: 0.1017 | acc: 97.72% | AUC: 0.993  | LR: 0.0005
Epoch  44 | train: 0.0781 | val: 0.1027 | acc: 97.69% | AUC: 0.993  | LR: 0.0005
Epoch  45 | train: 0.0777 | val: 0.0972 | acc: 97.90% | AUC: 0.993  | LR: 0.0005
Early stopping efter 46 epoker.
Klar!
Totalt antal utan m-komponent i K-fold poolen: 18848
Totalt antal med m-komponent i K-fold poolen: 2692
Total parameters: 15,710
--- Startar 10-Fold Cross Validation ---

========================================
 FOLD 1/10
========================================
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch   0 | train: 0.6121 | val: 0.5250 | acc: 86.35% | AUC: 0.798  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch   1 | train: 0.4654 | val: 0.4446 | acc: 87.00% | AUC: 0.846  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch   2 | train: 0.4311 | val: 0.4264 | acc: 88.72% | AUC: 0.859  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch   3 | train: 0.4128 | val: 0.4071 | acc: 85.19% | AUC: 0.875  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch   4 | train: 0.3981 | val: 0.4036 | acc: 91.78% | AUC: 0.884  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch   5 | train: 0.3844 | val: 0.3860 | acc: 90.02% | AUC: 0.889  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch   6 | train: 0.3707 | val: 0.3880 | acc: 92.11% | AUC: 0.893  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch   7 | train: 0.3616 | val: 0.3688 | acc: 88.95% | AUC: 0.896  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch   8 | train: 0.3516 | val: 0.3722 | acc: 92.53% | AUC: 0.901  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch   9 | train: 0.3474 | val: 0.3607 | acc: 89.51% | AUC: 0.902  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  10 | train: 0.3399 | val: 0.3571 | acc: 91.55% | AUC: 0.905  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  11 | train: 0.3298 | val: 0.3469 | acc: 90.20% | AUC: 0.911  | LR: 0.001
Epoch  12 | train: 0.3279 | val: 0.3693 | acc: 92.62% | AUC: 0.908  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  13 | train: 0.3186 | val: 0.3531 | acc: 92.01% | AUC: 0.914  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  14 | train: 0.3089 | val: 0.3457 | acc: 91.97% | AUC: 0.917  | LR: 0.001
Epoch  15 | train: 0.3061 | val: 0.3622 | acc: 93.13% | AUC: 0.915  | LR: 0.001
Epoch  16 | train: 0.2993 | val: 0.3416 | acc: 90.95% | AUC: 0.916  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  17 | train: 0.2945 | val: 0.3355 | acc: 89.04% | AUC: 0.918  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  18 | train: 0.2913 | val: 0.3311 | acc: 91.60% | AUC: 0.922  | LR: 0.001
Epoch  19 | train: 0.2848 | val: 0.3509 | acc: 91.83% | AUC: 0.917  | LR: 0.001
Epoch  20 | train: 0.2808 | val: 0.3573 | acc: 92.90% | AUC: 0.919  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  21 | train: 0.2745 | val: 0.3281 | acc: 90.95% | AUC: 0.924  | LR: 0.001
Epoch  22 | train: 0.2694 | val: 0.3258 | acc: 90.30% | AUC: 0.923  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  23 | train: 0.2525 | val: 0.3187 | acc: 90.48% | AUC: 0.927  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  24 | train: 0.2315 | val: 0.2922 | acc: 92.01% | AUC: 0.937  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  25 | train: 0.2130 | val: 0.2826 | acc: 95.87% | AUC: 0.946  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  26 | train: 0.1902 | val: 0.2743 | acc: 95.91% | AUC: 0.956  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  27 | train: 0.1722 | val: 0.2249 | acc: 96.10% | AUC: 0.972  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  28 | train: 0.1532 | val: 0.2258 | acc: 96.66% | AUC: 0.975  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  29 | train: 0.1346 | val: 0.1912 | acc: 96.19% | AUC: 0.978  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  30 | train: 0.1344 | val: 0.1738 | acc: 95.50% | AUC: 0.978  | LR: 0.001
Epoch  31 | train: 0.1251 | val: 0.1775 | acc: 94.71% | AUC: 0.977  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  32 | train: 0.1165 | val: 0.1733 | acc: 96.38% | AUC: 0.980  | LR: 0.001
Epoch  33 | train: 0.1141 | val: 0.1717 | acc: 96.24% | AUC: 0.979  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold1.pth
Epoch  34 | train: 0.1075 | val: 0.1587 | acc: 96.19% | AUC: 0.982  | LR: 0.001
Epoch  35 | train: 0.1089 | val: 0.1649 | acc: 95.64% | AUC: 0.980  | LR: 0.001
Epoch  36 | train: 0.1054 | val: 0.1628 | acc: 95.78% | AUC: 0.981  | LR: 0.001
Epoch  37 | train: 0.0976 | val: 0.1622 | acc: 95.17% | AUC: 0.981  | LR: 0.001
Epoch  38 | train: 0.1004 | val: 0.1661 | acc: 95.17% | AUC: 0.979  | LR: 0.001
Epoch  39 | train: 0.0942 | val: 0.1824 | acc: 96.43% | AUC: 0.979  | LR: 0.001
Epoch  40 | train: 0.0910 | val: 0.2017 | acc: 97.17% | AUC: 0.980  | LR: 0.001
Epoch  41 | train: 0.0934 | val: 0.1702 | acc: 96.05% | AUC: 0.980  | LR: 0.001
Epoch  42 | train: 0.0874 | val: 0.1918 | acc: 96.38% | AUC: 0.976  | LR: 0.001
Epoch  43 | train: 0.0833 | val: 0.1875 | acc: 96.84% | AUC: 0.981  | LR: 0.001
Epoch  44 | train: 0.0856 | val: 0.1721 | acc: 95.08% | AUC: 0.978  | LR: 0.001
Epoch  45 | train: 0.0828 | val: 0.1940 | acc: 96.61% | AUC: 0.980  | LR: 0.001
Epoch  46 | train: 0.0769 | val: 0.1962 | acc: 96.29% | AUC: 0.979  | LR: 0.001
Epoch  47 | train: 0.0785 | val: 0.1952 | acc: 96.38% | AUC: 0.981  | LR: 0.001
Epoch  48 | train: 0.0770 | val: 0.1907 | acc: 96.66% | AUC: 0.979  | LR: 0.001
Epoch  49 | train: 0.0832 | val: 0.1732 | acc: 94.43% | AUC: 0.978  | LR: 0.001
Early stopping efter 50 epoker.
Klar!

Utvärderar bästa modellen för Fold 1...
-> Slutresultat Fold 1: Train Loss: 0.0967 | Val Loss: 0.1587 | AUC: 0.9818

========================================
 FOLD 2/10
========================================
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch   0 | train: 0.6543 | val: 0.4616 | acc: 89.60% | AUC: 0.862  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch   1 | train: 0.4327 | val: 0.3377 | acc: 93.83% | AUC: 0.929  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch   2 | train: 0.3413 | val: 0.2685 | acc: 94.89% | AUC: 0.951  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch   3 | train: 0.2842 | val: 0.2280 | acc: 93.36% | AUC: 0.966  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch   4 | train: 0.2411 | val: 0.2201 | acc: 92.85% | AUC: 0.975  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch   5 | train: 0.2181 | val: 0.1791 | acc: 96.29% | AUC: 0.978  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch   6 | train: 0.2043 | val: 0.2020 | acc: 93.31% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch   7 | train: 0.1833 | val: 0.1677 | acc: 96.01% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch   8 | train: 0.1721 | val: 0.1940 | acc: 93.41% | AUC: 0.985  | LR: 0.001
Epoch   9 | train: 0.1744 | val: 0.1611 | acc: 96.05% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch  10 | train: 0.1615 | val: 0.1523 | acc: 96.43% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch  11 | train: 0.1509 | val: 0.1523 | acc: 96.24% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch  12 | train: 0.1459 | val: 0.1556 | acc: 95.59% | AUC: 0.987  | LR: 0.001
Epoch  13 | train: 0.1436 | val: 0.1498 | acc: 96.80% | AUC: 0.987  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold2.pth
Epoch  14 | train: 0.1370 | val: 0.1920 | acc: 92.71% | AUC: 0.987  | LR: 0.001
Epoch  15 | train: 0.1472 | val: 0.1513 | acc: 95.87% | AUC: 0.987  | LR: 0.001
Epoch  16 | train: 0.1289 | val: 0.1501 | acc: 96.66% | AUC: 0.986  | LR: 0.001
Epoch  17 | train: 0.1325 | val: 0.1478 | acc: 96.89% | AUC: 0.986  | LR: 0.001
Epoch  18 | train: 0.1181 | val: 0.1436 | acc: 96.52% | AUC: 0.987  | LR: 0.001
Epoch  19 | train: 0.1140 | val: 0.1448 | acc: 96.19% | AUC: 0.987  | LR: 0.001
Epoch  20 | train: 0.1148 | val: 0.1491 | acc: 96.84% | AUC: 0.985  | LR: 0.001
Epoch  21 | train: 0.1087 | val: 0.1438 | acc: 96.10% | AUC: 0.986  | LR: 0.001
Epoch  22 | train: 0.1031 | val: 0.1486 | acc: 96.80% | AUC: 0.986  | LR: 0.001
Epoch  23 | train: 0.1057 | val: 0.1457 | acc: 95.91% | AUC: 0.986  | LR: 0.001
Epoch  24 | train: 0.1016 | val: 0.1422 | acc: 96.43% | AUC: 0.986  | LR: 0.001
Epoch  25 | train: 0.0983 | val: 0.1458 | acc: 96.33% | AUC: 0.986  | LR: 0.001
Epoch  26 | train: 0.0961 | val: 0.1422 | acc: 96.70% | AUC: 0.985  | LR: 0.001
Epoch  27 | train: 0.0976 | val: 0.1548 | acc: 97.12% | AUC: 0.981  | LR: 0.001
Epoch  28 | train: 0.0941 | val: 0.1540 | acc: 96.52% | AUC: 0.983  | LR: 0.001
Epoch  29 | train: 0.0906 | val: 0.1537 | acc: 96.66% | AUC: 0.984  | LR: 0.001
Epoch  30 | train: 0.0885 | val: 0.1468 | acc: 96.38% | AUC: 0.985  | LR: 0.001
Epoch  31 | train: 0.0841 | val: 0.1530 | acc: 96.15% | AUC: 0.983  | LR: 0.001
Epoch  32 | train: 0.0831 | val: 0.1551 | acc: 94.85% | AUC: 0.986  | LR: 0.001
Epoch  33 | train: 0.0851 | val: 0.1546 | acc: 96.75% | AUC: 0.982  | LR: 0.001
Epoch  34 | train: 0.0843 | val: 0.1481 | acc: 95.82% | AUC: 0.981  | LR: 0.001
Epoch  35 | train: 0.0758 | val: 0.1602 | acc: 95.31% | AUC: 0.982  | LR: 0.001
Epoch  36 | train: 0.0729 | val: 0.1470 | acc: 96.43% | AUC: 0.986  | LR: 0.001
Epoch  37 | train: 0.0744 | val: 0.1508 | acc: 95.40% | AUC: 0.986  | LR: 0.001
Epoch  38 | train: 0.0755 | val: 0.1562 | acc: 94.71% | AUC: 0.986  | LR: 0.001
Epoch  39 | train: 0.0725 | val: 0.1536 | acc: 96.84% | AUC: 0.985  | LR: 0.001
Early stopping efter 40 epoker.
Klar!

Utvärderar bästa modellen för Fold 2...
-> Slutresultat Fold 2: Train Loss: 0.1594 | Val Loss: 0.1920 | AUC: 0.9874

========================================
 FOLD 3/10
========================================
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch   0 | train: 1.3277 | val: 0.4748 | acc: 88.86% | AUC: 0.846  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch   1 | train: 0.5544 | val: 0.4094 | acc: 92.53% | AUC: 0.896  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch   2 | train: 0.4357 | val: 0.3600 | acc: 89.51% | AUC: 0.922  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch   3 | train: 0.3699 | val: 0.3343 | acc: 91.50% | AUC: 0.935  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch   4 | train: 0.3441 | val: 0.3209 | acc: 93.64% | AUC: 0.940  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch   5 | train: 0.3051 | val: 0.2913 | acc: 94.34% | AUC: 0.949  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch   6 | train: 0.2798 | val: 0.2666 | acc: 93.18% | AUC: 0.961  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch   7 | train: 0.2554 | val: 0.2423 | acc: 94.38% | AUC: 0.967  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch   8 | train: 0.2308 | val: 0.2290 | acc: 94.75% | AUC: 0.972  | LR: 0.001
Epoch   9 | train: 0.2286 | val: 0.2482 | acc: 95.96% | AUC: 0.971  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch  10 | train: 0.2268 | val: 0.2426 | acc: 95.78% | AUC: 0.972  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch  11 | train: 0.2096 | val: 0.2264 | acc: 95.59% | AUC: 0.973  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch  12 | train: 0.2043 | val: 0.2035 | acc: 94.85% | AUC: 0.975  | LR: 0.001
Epoch  13 | train: 0.1905 | val: 0.2044 | acc: 94.75% | AUC: 0.971  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch  14 | train: 0.1904 | val: 0.2185 | acc: 96.19% | AUC: 0.976  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch  15 | train: 0.1749 | val: 0.2186 | acc: 96.33% | AUC: 0.977  | LR: 0.001
Epoch  16 | train: 0.1872 | val: 0.2002 | acc: 94.71% | AUC: 0.976  | LR: 0.001
Epoch  17 | train: 0.1655 | val: 0.2013 | acc: 93.27% | AUC: 0.975  | LR: 0.001
Epoch  18 | train: 0.1706 | val: 0.1965 | acc: 95.91% | AUC: 0.976  | LR: 0.001
Epoch  19 | train: 0.1626 | val: 0.2120 | acc: 95.82% | AUC: 0.974  | LR: 0.001
Epoch  20 | train: 0.1554 | val: 0.2037 | acc: 95.54% | AUC: 0.973  | LR: 0.001
Epoch  21 | train: 0.1529 | val: 0.1931 | acc: 94.01% | AUC: 0.976  | LR: 0.001
Epoch  22 | train: 0.1449 | val: 0.2077 | acc: 96.05% | AUC: 0.977  | LR: 0.001
Epoch  23 | train: 0.1433 | val: 0.2017 | acc: 93.78% | AUC: 0.975  | LR: 0.001
Epoch  24 | train: 0.1385 | val: 0.1938 | acc: 94.15% | AUC: 0.973  | LR: 0.001
Epoch  25 | train: 0.1368 | val: 0.2080 | acc: 96.24% | AUC: 0.975  | LR: 0.001
Epoch  26 | train: 0.1320 | val: 0.2186 | acc: 96.10% | AUC: 0.977  | LR: 0.001
Epoch  27 | train: 0.1399 | val: 0.1866 | acc: 93.55% | AUC: 0.977  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch  28 | train: 0.1385 | val: 0.2307 | acc: 96.24% | AUC: 0.978  | LR: 0.001
Epoch  29 | train: 0.1300 | val: 0.1893 | acc: 93.59% | AUC: 0.976  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold3.pth
Epoch  30 | train: 0.1268 | val: 0.1951 | acc: 95.59% | AUC: 0.978  | LR: 0.001
Epoch  31 | train: 0.1170 | val: 0.2076 | acc: 95.96% | AUC: 0.976  | LR: 0.001
Epoch  32 | train: 0.1090 | val: 0.2015 | acc: 95.96% | AUC: 0.975  | LR: 0.001
Epoch  33 | train: 0.1100 | val: 0.2021 | acc: 94.99% | AUC: 0.973  | LR: 0.001
Epoch  34 | train: 0.1118 | val: 0.2445 | acc: 96.38% | AUC: 0.975  | LR: 0.001
Epoch  35 | train: 0.1213 | val: 0.2177 | acc: 96.38% | AUC: 0.977  | LR: 0.001
Epoch  36 | train: 0.1078 | val: 0.2079 | acc: 95.59% | AUC: 0.977  | LR: 0.001
Epoch  37 | train: 0.1050 | val: 0.2000 | acc: 95.68% | AUC: 0.976  | LR: 0.001
Epoch  38 | train: 0.1049 | val: 0.1931 | acc: 95.68% | AUC: 0.977  | LR: 0.001
Epoch  39 | train: 0.0985 | val: 0.2229 | acc: 96.47% | AUC: 0.976  | LR: 0.001
Epoch  40 | train: 0.0980 | val: 0.2006 | acc: 94.94% | AUC: 0.975  | LR: 0.001
Epoch  41 | train: 0.1023 | val: 0.2629 | acc: 96.52% | AUC: 0.975  | LR: 0.001
Epoch  42 | train: 0.0967 | val: 0.2424 | acc: 96.24% | AUC: 0.974  | LR: 0.001
Early stopping efter 43 epoker.
Klar!

Utvärderar bästa modellen för Fold 3...
-> Slutresultat Fold 3: Train Loss: 0.1022 | Val Loss: 0.1951 | AUC: 0.9784

========================================
 FOLD 4/10
========================================
  -> ny bästa modell sparad till ../models/cnn_tiny_fold4.pth
Epoch   0 | train: 2.0914 | val: 0.6225 | acc: 86.52% | AUC: 0.775  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold4.pth
Epoch   1 | train: 0.6921 | val: 0.4359 | acc: 88.61% | AUC: 0.885  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold4.pth
Epoch   2 | train: 0.4573 | val: 0.3994 | acc: 91.03% | AUC: 0.911  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_tiny_fold4.pth
Epoch   3 | train: 0.3754 | val: 0.3830 | acc: 93.49% | AUC: 0.930  | LR: 0.001

,fold,train_loss,val_loss,val_accuracy,val_auc,val_spec,val_sens,tn,fp,fn,tp
0,1,0.096663,0.158665,96.193129,0.981837,0.969214,0.911111,1826,58,24,246
1,2,0.159428,0.192048,92.711235,0.987351,0.921975,0.962963,1737,147,10,260
2,3,0.102233,0.195060,95.589601,0.978423,0.969231,0.862454,1827,58,37,232
3,4,0.073041,0.194257,97.396560,0.981717,0.981403,0.921933,1847,35,21,248
4,5,0.103076,0.173158,95.169531,0.983121,0.955414,0.925651,1800,84,20,249
5,6,0.120821,0.121275,96.189591,0.990747,0.963356,0.951673,1814,69,13,256
6,7,0.092831,0.185254,97.770553,0.981825,0.992569,0.873606,1870,14,34,235
7,8,0.084634,0.267743,96.703807,0.976472,0.985676,0.836431,1858,27,44,225
8,9,0.140555,0.294323,93.268338,0.963748,0.936340,0.907063,1765,120,25,244
9,10,0.095692,0.133943,95.304510,0.988618,0.953773,0.947955,1795,87,14,255

In [2]:
import duckdb
from functions.evaluation import evaluate
from networks.cnn_small import CNNModel
from networks.cnn_network import build_dataloaders


con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


train_rows = df[df['set'] == 'train']
val_rows   = df[df['set'] == 'val']
test_rows  = df[df['set'] == 'test']

drop_indices = train_rows[train_rows['label'] == 0].sample(frac=0.7).index

train_rows = train_rows.drop(drop_indices)
train_rows = train_rows[train_rows['label'].isin([0,1])]
val_rows = val_rows[val_rows['label'].isin([0,1])]

print(f"Antal utan m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 0])}")
print(f"Antal med m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 1])}")

CNN = CNNModel()
cnn_train_dl, cnn_val_dl, _ = build_dataloaders(train_rows, val_rows, val_rows)
CNN.reset_weights()
CNN.retrain(cnn_train_dl,cnn_val_dl,patience=15)

con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


k_fold_rows = df[df['set'].isin(['train','val']) ].copy()
k_fold_rows = k_fold_rows[k_fold_rows['label'].isin([0,1])]
drop_indices = k_fold_rows[k_fold_rows['label'] == 0].sample(frac=0.7).index
k_fold_rows = k_fold_rows.drop(drop_indices)
print(f"Totalt antal utan m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 0])}")
print(f"Totalt antal med m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 1])}")

test_rows  = df[df['set'] == 'test']


CNN = CNNModel()
CNN.retrain_with_k_fold(k_fold_rows)

Antal utan m-komponent i träningsdatan: 17903
Antal med m-komponent i träningsdatan: 2553
Total parameters: 45,266
  -> ny bästa modell sparad till ../models/cnn_small.pth
Epoch   0 | train: 0.9604 | val: 0.4805 | acc: 90.08% | AUC: 0.909  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small.pth
Epoch   1 | train: 0.4255 | val: 0.2241 | acc: 97.99% | AUC: 0.973  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small.pth
Epoch   2 | train: 0.2874 | val: 0.2167 | acc: 96.14% | AUC: 0.989  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small.pth
Epoch   3 | train: 0.2078 | val: 0.1112 | acc: 98.11% | AUC: 0.996  | LR: 0.001
Epoch   4 | train: 0.1942 | val: 0.1243 | acc: 97.51% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small.pth
Epoch   5 | train: 0.1873 | val: 0.1007 | acc: 98.45% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small.pth
Epoch   6 | train: 0.1591 | val: 0.1542 | acc: 95.92% | AUC: 0.997  | LR: 0.001
Epoch   7 | train: 0.1443 | val: 0.0940 | acc: 97.99% | AUC: 0.997  | LR: 0.001
Epoch   8 | train: 0.1392 | val: 0.0856 | acc: 98.42% | AUC: 0.996  | LR: 0.001
Epoch   9 | train: 0.1327 | val: 0.0956 | acc: 98.05% | AUC: 0.996  | LR: 0.001
Epoch  10 | train: 0.1275 | val: 0.0851 | acc: 98.48% | AUC: 0.996  | LR: 0.001
Epoch  11 | train: 0.1330 | val: 0.1130 | acc: 97.23% | AUC: 0.995  | LR: 0.001
Epoch  12 | train: 0.1328 | val: 0.1310 | acc: 96.44% | AUC: 0.996  | LR: 0.001
Epoch  13 | train: 0.1243 | val: 0.0918 | acc: 97.75% | AUC: 0.994  | LR: 0.001
Epoch  14 | train: 0.1191 | val: 0.1116 | acc: 97.29% | AUC: 0.995  | LR: 0.001
Epoch  15 | train: 0.1217 | val: 0.0760 | acc: 98.45% | AUC: 0.995  | LR: 0.001
Epoch  16 | train: 0.1085 | val: 0.0752 | acc: 98.48% | AUC: 0.994  | LR: 0.001
Epoch  17 | train: 0.1070 | val: 0.0700 | acc: 98.78% | AUC: 0.995  | LR: 0.001
Epoch  18 | train: 0.1105 | val: 0.0755 | acc: 98.21% | AUC: 0.995  | LR: 0.001
Epoch  19 | train: 0.1008 | val: 0.0825 | acc: 98.05% | AUC: 0.994  | LR: 0.001
Epoch  20 | train: 0.1048 | val: 0.1317 | acc: 95.38% | AUC: 0.994  | LR: 0.001
Epoch  21 | train: 0.1029 | val: 0.0685 | acc: 98.48% | AUC: 0.996  | LR: 0.001
Epoch  22 | train: 0.0950 | val: 0.0748 | acc: 98.30% | AUC: 0.994  | LR: 0.001
Epoch  23 | train: 0.0887 | val: 0.0815 | acc: 97.69% | AUC: 0.995  | LR: 0.001
Epoch  24 | train: 0.0857 | val: 0.0843 | acc: 97.60% | AUC: 0.995  | LR: 0.001
Epoch  25 | train: 0.0861 | val: 0.0850 | acc: 97.90% | AUC: 0.993  | LR: 0.001
Epoch  26 | train: 0.0920 | val: 0.0777 | acc: 97.78% | AUC: 0.996  | LR: 0.001
Epoch  27 | train: 0.0839 | val: 0.0758 | acc: 98.66% | AUC: 0.990  | LR: 0.001
Epoch  28 | train: 0.0822 | val: 0.0799 | acc: 97.81% | AUC: 0.993  | LR: 0.001
Epoch  29 | train: 0.0753 | val: 0.0819 | acc: 97.47% | AUC: 0.995  | LR: 0.001
Epoch  30 | train: 0.0717 | val: 0.0811 | acc: 97.84% | AUC: 0.994  | LR: 0.001
Epoch  31 | train: 0.0755 | val: 0.0707 | acc: 98.48% | AUC: 0.994  | LR: 0.001
Epoch  32 | train: 0.0720 | val: 0.1043 | acc: 96.41% | AUC: 0.993  | LR: 0.001
Epoch  33 | train: 0.0669 | val: 0.0826 | acc: 97.69% | AUC: 0.993  | LR: 0.001
Epoch  34 | train: 0.0669 | val: 0.0972 | acc: 97.08% | AUC: 0.991  | LR: 0.001
Epoch  35 | train: 0.0662 | val: 0.0739 | acc: 98.33% | AUC: 0.994  | LR: 0.001
Epoch  36 | train: 0.0639 | val: 0.0883 | acc: 97.51% | AUC: 0.992  | LR: 0.001
Early stopping efter 37 epoker.
Klar!
Totalt antal utan m-komponent i K-fold poolen: 18848
Totalt antal med m-komponent i K-fold poolen: 2692
Total parameters: 45,266
--- Startar 10-Fold Cross Validation ---

========================================
 FOLD 1/10
========================================
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch   0 | train: 1.4297 | val: 0.5136 | acc: 88.72% | AUC: 0.802  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch   1 | train: 0.4719 | val: 0.4604 | acc: 91.32% | AUC: 0.865  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch   2 | train: 0.4005 | val: 0.3828 | acc: 92.25% | AUC: 0.904  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch   3 | train: 0.3470 | val: 0.3488 | acc: 89.46% | AUC: 0.919  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch   4 | train: 0.3105 | val: 0.3253 | acc: 93.41% | AUC: 0.929  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch   5 | train: 0.2917 | val: 0.3144 | acc: 93.13% | AUC: 0.932  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch   6 | train: 0.2694 | val: 0.3003 | acc: 94.10% | AUC: 0.942  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch   7 | train: 0.2513 | val: 0.3124 | acc: 95.45% | AUC: 0.953  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch   8 | train: 0.2321 | val: 0.3087 | acc: 95.45% | AUC: 0.958  | LR: 0.001
Epoch   9 | train: 0.2375 | val: 0.2615 | acc: 94.15% | AUC: 0.956  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  10 | train: 0.2167 | val: 0.2448 | acc: 95.78% | AUC: 0.969  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  11 | train: 0.1928 | val: 0.2484 | acc: 95.87% | AUC: 0.971  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  12 | train: 0.1784 | val: 0.2055 | acc: 95.03% | AUC: 0.974  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  13 | train: 0.1750 | val: 0.2918 | acc: 96.29% | AUC: 0.976  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  14 | train: 0.1799 | val: 0.2095 | acc: 96.43% | AUC: 0.977  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  15 | train: 0.1597 | val: 0.1813 | acc: 95.08% | AUC: 0.979  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  16 | train: 0.1480 | val: 0.1751 | acc: 94.99% | AUC: 0.980  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  17 | train: 0.1492 | val: 0.1691 | acc: 96.10% | AUC: 0.982  | LR: 0.001
Epoch  18 | train: 0.1398 | val: 0.2367 | acc: 96.80% | AUC: 0.980  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  19 | train: 0.1549 | val: 0.1881 | acc: 96.84% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  20 | train: 0.1406 | val: 0.2120 | acc: 97.03% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  21 | train: 0.1408 | val: 0.1809 | acc: 97.21% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  22 | train: 0.1276 | val: 0.1555 | acc: 96.89% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  23 | train: 0.1260 | val: 0.1574 | acc: 95.64% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  24 | train: 0.1284 | val: 0.1544 | acc: 96.84% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  25 | train: 0.1175 | val: 0.1480 | acc: 96.33% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  26 | train: 0.1094 | val: 0.1569 | acc: 97.12% | AUC: 0.988  | LR: 0.001
Epoch  27 | train: 0.1150 | val: 0.1452 | acc: 95.68% | AUC: 0.987  | LR: 0.001
Epoch  28 | train: 0.1104 | val: 0.1529 | acc: 96.15% | AUC: 0.987  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  29 | train: 0.1092 | val: 0.1416 | acc: 96.80% | AUC: 0.988  | LR: 0.001
Epoch  30 | train: 0.1053 | val: 0.1470 | acc: 95.87% | AUC: 0.987  | LR: 0.001
Epoch  31 | train: 0.1107 | val: 0.1454 | acc: 96.52% | AUC: 0.988  | LR: 0.001
Epoch  32 | train: 0.1019 | val: 0.1712 | acc: 97.31% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold1.pth
Epoch  33 | train: 0.0949 | val: 0.1839 | acc: 97.63% | AUC: 0.989  | LR: 0.001
Epoch  34 | train: 0.0937 | val: 0.1763 | acc: 97.26% | AUC: 0.988  | LR: 0.001
Epoch  35 | train: 0.0929 | val: 0.1456 | acc: 96.10% | AUC: 0.988  | LR: 0.001
Epoch  36 | train: 0.0908 | val: 0.1711 | acc: 97.03% | AUC: 0.987  | LR: 0.001
Epoch  37 | train: 0.0936 | val: 0.1847 | acc: 97.17% | AUC: 0.987  | LR: 0.001
Epoch  38 | train: 0.0895 | val: 0.1655 | acc: 96.47% | AUC: 0.987  | LR: 0.001
Epoch  39 | train: 0.0876 | val: 0.1938 | acc: 97.45% | AUC: 0.988  | LR: 0.001
Epoch  40 | train: 0.0873 | val: 0.1739 | acc: 96.19% | AUC: 0.986  | LR: 0.001
Epoch  41 | train: 0.0838 | val: 0.1643 | acc: 97.21% | AUC: 0.989  | LR: 0.001
Epoch  42 | train: 0.0868 | val: 0.1854 | acc: 97.08% | AUC: 0.987  | LR: 0.001
Epoch  43 | train: 0.0845 | val: 0.1502 | acc: 96.94% | AUC: 0.989  | LR: 0.001
Epoch  44 | train: 0.0922 | val: 0.1816 | acc: 97.17% | AUC: 0.987  | LR: 0.001
Early stopping efter 45 epoker.
Klar!

Utvärderar bästa modellen för Fold 1...
-> Slutresultat Fold 1: Train Loss: 0.0990 | Val Loss: 0.1839 | AUC: 0.9889

========================================
 FOLD 2/10
========================================
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch   0 | train: 0.9407 | val: 0.5534 | acc: 91.64% | AUC: 0.782  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch   1 | train: 0.4771 | val: 0.3917 | acc: 93.69% | AUC: 0.919  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch   2 | train: 0.3435 | val: 0.2913 | acc: 91.69% | AUC: 0.954  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch   3 | train: 0.2700 | val: 0.2212 | acc: 95.73% | AUC: 0.968  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch   4 | train: 0.2238 | val: 0.1895 | acc: 95.45% | AUC: 0.979  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch   5 | train: 0.1954 | val: 0.1974 | acc: 92.76% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch   6 | train: 0.1900 | val: 0.1447 | acc: 96.84% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch   7 | train: 0.1643 | val: 0.1343 | acc: 96.80% | AUC: 0.987  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch   8 | train: 0.1559 | val: 0.1277 | acc: 96.98% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch   9 | train: 0.1523 | val: 0.1376 | acc: 97.31% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch  10 | train: 0.1493 | val: 0.1240 | acc: 96.94% | AUC: 0.989  | LR: 0.001
Epoch  11 | train: 0.1410 | val: 0.1296 | acc: 96.38% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch  12 | train: 0.1252 | val: 0.1152 | acc: 97.17% | AUC: 0.990  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch  13 | train: 0.1354 | val: 0.1214 | acc: 96.05% | AUC: 0.990  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch  14 | train: 0.1240 | val: 0.1293 | acc: 95.45% | AUC: 0.991  | LR: 0.001
Epoch  15 | train: 0.1235 | val: 0.1114 | acc: 97.49% | AUC: 0.990  | LR: 0.001
Epoch  16 | train: 0.1165 | val: 0.1133 | acc: 97.86% | AUC: 0.991  | LR: 0.001
Epoch  17 | train: 0.1115 | val: 0.1102 | acc: 97.08% | AUC: 0.990  | LR: 0.001
Epoch  18 | train: 0.1214 | val: 0.1341 | acc: 95.73% | AUC: 0.990  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch  19 | train: 0.1096 | val: 0.1093 | acc: 97.77% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch  20 | train: 0.1083 | val: 0.1047 | acc: 96.89% | AUC: 0.992  | LR: 0.001
Epoch  21 | train: 0.1008 | val: 0.1097 | acc: 97.12% | AUC: 0.991  | LR: 0.001
Epoch  22 | train: 0.0954 | val: 0.1048 | acc: 97.68% | AUC: 0.991  | LR: 0.001
Epoch  23 | train: 0.0980 | val: 0.1050 | acc: 97.96% | AUC: 0.991  | LR: 0.001
Epoch  24 | train: 0.0943 | val: 0.1033 | acc: 97.59% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch  25 | train: 0.0890 | val: 0.0978 | acc: 97.17% | AUC: 0.992  | LR: 0.001
Epoch  26 | train: 0.0866 | val: 0.1136 | acc: 96.33% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch  27 | train: 0.0897 | val: 0.1360 | acc: 93.92% | AUC: 0.992  | LR: 0.001
Epoch  28 | train: 0.0879 | val: 0.0994 | acc: 97.49% | AUC: 0.992  | LR: 0.001
Epoch  29 | train: 0.0823 | val: 0.1230 | acc: 95.54% | AUC: 0.991  | LR: 0.001
Epoch  30 | train: 0.0870 | val: 0.1160 | acc: 95.36% | AUC: 0.991  | LR: 0.001
Epoch  31 | train: 0.0835 | val: 0.1129 | acc: 97.49% | AUC: 0.991  | LR: 0.001
Epoch  32 | train: 0.0799 | val: 0.1124 | acc: 96.15% | AUC: 0.991  | LR: 0.001
Epoch  33 | train: 0.0780 | val: 0.1084 | acc: 97.12% | AUC: 0.991  | LR: 0.001
Epoch  34 | train: 0.0718 | val: 0.1089 | acc: 96.80% | AUC: 0.991  | LR: 0.001
Epoch  35 | train: 0.0733 | val: 0.1054 | acc: 97.49% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch  36 | train: 0.0718 | val: 0.1127 | acc: 98.00% | AUC: 0.992  | LR: 0.001
Epoch  37 | train: 0.0691 | val: 0.1077 | acc: 97.31% | AUC: 0.991  | LR: 0.001
Epoch  38 | train: 0.0695 | val: 0.1044 | acc: 97.63% | AUC: 0.992  | LR: 0.001
Epoch  39 | train: 0.0690 | val: 0.1104 | acc: 97.49% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold2.pth
Epoch  40 | train: 0.0700 | val: 0.1052 | acc: 96.33% | AUC: 0.993  | LR: 0.001
Early stopping efter 41 epoker.
Klar!

Utvärderar bästa modellen för Fold 2...
-> Slutresultat Fold 2: Train Loss: 0.0628 | Val Loss: 0.1052 | AUC: 0.9928

========================================
 FOLD 3/10
========================================
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch   0 | train: 0.9683 | val: 0.4764 | acc: 91.36% | AUC: 0.842  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch   1 | train: 0.4509 | val: 0.3811 | acc: 88.16% | AUC: 0.920  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch   2 | train: 0.3511 | val: 0.3096 | acc: 94.66% | AUC: 0.950  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch   3 | train: 0.2871 | val: 0.2689 | acc: 95.49% | AUC: 0.959  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch   4 | train: 0.2588 | val: 0.2489 | acc: 96.10% | AUC: 0.965  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch   5 | train: 0.2308 | val: 0.2226 | acc: 95.68% | AUC: 0.969  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch   6 | train: 0.2141 | val: 0.2208 | acc: 94.84% | AUC: 0.969  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch   7 | train: 0.2073 | val: 0.2510 | acc: 96.84% | AUC: 0.970  | LR: 0.001
Epoch   8 | train: 0.2020 | val: 0.2116 | acc: 94.38% | AUC: 0.970  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch   9 | train: 0.1824 | val: 0.2033 | acc: 96.56% | AUC: 0.975  | LR: 0.001
Epoch  10 | train: 0.1756 | val: 0.1957 | acc: 95.17% | AUC: 0.974  | LR: 0.001
Epoch  11 | train: 0.1723 | val: 0.1963 | acc: 96.56% | AUC: 0.974  | LR: 0.001
Epoch  12 | train: 0.1604 | val: 0.2156 | acc: 97.03% | AUC: 0.974  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch  13 | train: 0.1610 | val: 0.2105 | acc: 96.89% | AUC: 0.975  | LR: 0.001
Epoch  14 | train: 0.1592 | val: 0.2555 | acc: 97.17% | AUC: 0.975  | LR: 0.001
Epoch  15 | train: 0.1492 | val: 0.2057 | acc: 95.45% | AUC: 0.974  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch  16 | train: 0.1399 | val: 0.1964 | acc: 96.75% | AUC: 0.976  | LR: 0.001
Epoch  17 | train: 0.1356 | val: 0.2193 | acc: 97.07% | AUC: 0.975  | LR: 0.001
Epoch  18 | train: 0.1485 | val: 0.2171 | acc: 97.35% | AUC: 0.973  | LR: 0.001
Epoch  19 | train: 0.1269 | val: 0.2099 | acc: 96.93% | AUC: 0.975  | LR: 0.001
Epoch  20 | train: 0.1293 | val: 0.2213 | acc: 96.98% | AUC: 0.974  | LR: 0.001
Epoch  21 | train: 0.1223 | val: 0.1848 | acc: 96.93% | AUC: 0.974  | LR: 0.001
Epoch  22 | train: 0.1354 | val: 0.2285 | acc: 97.21% | AUC: 0.973  | LR: 0.001
Epoch  23 | train: 0.1240 | val: 0.2457 | acc: 97.21% | AUC: 0.972  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold3.pth
Epoch  24 | train: 0.1243 | val: 0.1865 | acc: 96.61% | AUC: 0.977  | LR: 0.001
Epoch  25 | train: 0.1164 | val: 0.2461 | acc: 97.26% | AUC: 0.975  | LR: 0.001
Epoch  26 | train: 0.1153 | val: 0.1963 | acc: 97.17% | AUC: 0.973  | LR: 0.001
Epoch  27 | train: 0.1200 | val: 0.1872 | acc: 96.01% | AUC: 0.974  | LR: 0.001
Epoch  28 | train: 0.1126 | val: 0.2251 | acc: 97.12% | AUC: 0.968  | LR: 0.001
Epoch  29 | train: 0.1073 | val: 0.2012 | acc: 96.47% | AUC: 0.970  | LR: 0.001
Epoch  30 | train: 0.1040 | val: 0.2080 | acc: 97.26% | AUC: 0.973  | LR: 0.001
Epoch  31 | train: 0.1090 | val: 0.1931 | acc: 97.35% | AUC: 0.975  | LR: 0.001
Epoch  32 | train: 0.0981 | val: 0.1995 | acc: 96.80% | AUC: 0.972  | LR: 0.001
Epoch  33 | train: 0.0933 | val: 0.2600 | acc: 97.21% | AUC: 0.971  | LR: 0.001
Epoch  34 | train: 0.0958 | val: 0.1965 | acc: 95.12% | AUC: 0.972  | LR: 0.001
Epoch  35 | train: 0.0885 | val: 0.2325 | acc: 97.07% | AUC: 0.972  | LR: 0.001
Epoch  36 | train: 0.0899 | val: 0.1874 | acc: 95.68% | AUC: 0.971  | LR: 0.001
Early stopping efter 37 epoker.
Klar!

Utvärderar bästa modellen för Fold 3...
-> Slutresultat Fold 3: Train Loss: 0.0980 | Val Loss: 0.1865 | AUC: 0.9771

========================================
 FOLD 4/10
========================================
  -> ny bästa modell sparad till ../models/cnn_small_fold4.pth
Epoch   0 | train: 2.4047 | val: 0.5063 | acc: 89.78% | AUC: 0.806  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold4.pth
Epoch   1 | train: 0.5664 | val: 0.4432 | acc: 92.15% | AUC: 0.872  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold4.pth
Epoch   2 | train: 0.4402 | val: 0.3893 | acc: 93.03% | AUC: 0.915  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold4.pth
Epoch   3 | train: 0.3315 | val: 0.3001 | acc: 92.98% | AUC: 0.950  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold4.pth
Epoch   4 | train: 0.2861 | val: 0.2707 | acc: 92.24% | AUC: 0.967  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold4.pth
Epoch   5 | train: 0.2528 | val: 0.2349 | acc: 95.68% | AUC: 0.973  | LR: 0.001
Epoch   6 | train: 0.2213 | val: 0.2539 | acc: 95.77% | AUC: 0.970  | LR: 0.001
Epoch   7 | train: 0.1948 | val: 0.2339 | acc: 96.24% | AUC: 0.970  | LR: 0.001
Epoch   8 | train: 0.2133 | val: 0.2738 | acc: 96.00% | AUC: 0.970  | LR: 0.001
Epoch   9 | train: 0.1869 | val: 0.2373 | acc: 96.10% | AUC: 0.968  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold4.pth
Epoch  10 | train: 0.1694 | val: 0.1971 | acc: 96.75% | AUC: 0.980  | LR: 0.001
Epoch  11 | train: 0.1682 | val: 0.2159 | acc: 96.33% | AUC: 0.973  | LR: 0.001
Epoch  12 | train: 0.1560 | val: 0.1985 | acc: 96.14% | AUC: 0.976  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold4.pth
Epoch  13 | train: 0.1475 | val: 0.1806 | acc: 96.33% | AUC: 0.981  | LR: 0.001
Epoch  14 | train: 0.1459 | val: 0.1828 | acc: 95.35% | AUC: 0.980  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold4.pth
Epoch  15 | train: 0.1320 | val: 0.1903 | acc: 94.28% | AUC: 0.981  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_small_fold4.pth

,fold,train_loss,val_loss,val_accuracy,val_auc,val_spec,val_sens,tn,fp,fn,tp
0,1,0.099035,0.183867,97.632312,0.988936,0.988854,0.888889,1863,21,30,240
1,2,0.062801,0.105218,96.332405,0.992785,0.962845,0.966667,1814,70,9,261
2,3,0.097995,0.186478,96.609382,0.977072,0.977176,0.888476,1841,43,30,239
3,4,0.098791,0.178832,97.211896,0.983592,0.983006,0.895911,1851,32,28,241
4,5,0.128195,0.155325,94.196843,0.992399,0.936870,0.977695,1766,119,6,263
5,6,0.054150,0.099408,97.211896,0.991754,0.977164,0.936803,1840,43,17,252
6,7,0.083843,0.093577,97.353760,0.992723,0.977719,0.944238,1843,42,15,254
7,8,0.105868,0.226219,97.260910,0.980718,0.990451,0.847584,1867,18,41,228
8,9,0.106469,0.504116,96.425255,0.973250,0.975597,0.884758,1839,46,31,238
9,10,0.091266,0.126549,95.724907,0.988275,0.962294,0.921933,1812,71,21,248

In [3]:
import duckdb
from functions.evaluation import evaluate
from networks.cnn_medium import CNNModel
from networks.cnn_network import build_dataloaders


con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


train_rows = df[df['set'] == 'train']
val_rows   = df[df['set'] == 'val']
test_rows  = df[df['set'] == 'test']

drop_indices = train_rows[train_rows['label'] == 0].sample(frac=0.7).index

train_rows = train_rows.drop(drop_indices)
train_rows = train_rows[train_rows['label'].isin([0,1])]
val_rows = val_rows[val_rows['label'].isin([0,1])]

print(f"Antal utan m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 0])}")
print(f"Antal med m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 1])}")

CNN = CNNModel()
cnn_train_dl, cnn_val_dl, _ = build_dataloaders(train_rows, val_rows, val_rows)
CNN.reset_weights()
CNN.retrain(cnn_train_dl,cnn_val_dl,patience=15)

con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


k_fold_rows = df[df['set'].isin(['train','val']) ].copy()
k_fold_rows = k_fold_rows[k_fold_rows['label'].isin([0,1])]
drop_indices = k_fold_rows[k_fold_rows['label'] == 0].sample(frac=0.7).index
k_fold_rows = k_fold_rows.drop(drop_indices)
print(f"Totalt antal utan m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 0])}")
print(f"Totalt antal med m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 1])}")

test_rows  = df[df['set'] == 'test']


CNN = CNNModel()
CNN.retrain_with_k_fold(k_fold_rows)

Antal utan m-komponent i träningsdatan: 17903
Antal med m-komponent i träningsdatan: 2553
Total parameters: 172,130
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch   0 | train: 3.1926 | val: 0.4294 | acc: 96.87% | AUC: 0.821  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch   1 | train: 0.5033 | val: 0.4425 | acc: 89.60% | AUC: 0.936  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch   2 | train: 0.3814 | val: 0.2229 | acc: 96.96% | AUC: 0.978  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch   3 | train: 0.2843 | val: 0.2086 | acc: 95.13% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch   4 | train: 0.2361 | val: 0.2070 | acc: 94.43% | AUC: 0.993  | LR: 0.001
Epoch   5 | train: 0.2322 | val: 0.2299 | acc: 94.65% | AUC: 0.983  | LR: 0.001
Epoch   6 | train: 0.2199 | val: 0.2704 | acc: 90.20% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch   7 | train: 0.1980 | val: 0.1097 | acc: 97.47% | AUC: 0.996  | LR: 0.001
Epoch   8 | train: 0.1670 | val: 0.0951 | acc: 98.24% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch   9 | train: 0.1601 | val: 0.0790 | acc: 98.81% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch  10 | train: 0.1490 | val: 0.1134 | acc: 97.35% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch  11 | train: 0.1353 | val: 0.1267 | acc: 97.17% | AUC: 0.997  | LR: 0.001
Epoch  12 | train: 0.1482 | val: 0.1302 | acc: 96.26% | AUC: 0.996  | LR: 0.001
Epoch  13 | train: 0.1304 | val: 0.0846 | acc: 98.24% | AUC: 0.997  | LR: 0.001
Epoch  14 | train: 0.1262 | val: 0.0748 | acc: 98.84% | AUC: 0.997  | LR: 0.001
Epoch  15 | train: 0.1320 | val: 0.0750 | acc: 98.66% | AUC: 0.996  | LR: 0.001
Epoch  16 | train: 0.1171 | val: 0.1113 | acc: 97.05% | AUC: 0.997  | LR: 0.001
Epoch  17 | train: 0.1104 | val: 0.0738 | acc: 98.57% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch  18 | train: 0.1101 | val: 0.1068 | acc: 97.02% | AUC: 0.997  | LR: 0.001
Epoch  19 | train: 0.1056 | val: 0.0662 | acc: 98.84% | AUC: 0.997  | LR: 0.001
Epoch  20 | train: 0.1071 | val: 0.0892 | acc: 97.84% | AUC: 0.997  | LR: 0.001
Epoch  21 | train: 0.0989 | val: 0.0821 | acc: 97.93% | AUC: 0.997  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch  22 | train: 0.0964 | val: 0.0673 | acc: 98.66% | AUC: 0.997  | LR: 0.001
Epoch  23 | train: 0.0919 | val: 0.1123 | acc: 96.41% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch  24 | train: 0.0910 | val: 0.0606 | acc: 98.84% | AUC: 0.997  | LR: 0.001
Epoch  25 | train: 0.1043 | val: 0.0592 | acc: 98.87% | AUC: 0.997  | LR: 0.001
Epoch  26 | train: 0.0935 | val: 0.1108 | acc: 96.53% | AUC: 0.997  | LR: 0.001
Epoch  27 | train: 0.0891 | val: 0.1534 | acc: 94.40% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch  28 | train: 0.0889 | val: 0.0782 | acc: 97.84% | AUC: 0.997  | LR: 0.001
Epoch  29 | train: 0.0802 | val: 0.0877 | acc: 97.32% | AUC: 0.997  | LR: 0.001
Epoch  30 | train: 0.0817 | val: 0.0634 | acc: 98.63% | AUC: 0.997  | LR: 0.001
Epoch  31 | train: 0.0776 | val: 0.0552 | acc: 98.94% | AUC: 0.997  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch  32 | train: 0.0743 | val: 0.0578 | acc: 98.90% | AUC: 0.997  | LR: 0.001
Epoch  33 | train: 0.0773 | val: 0.1092 | acc: 96.17% | AUC: 0.997  | LR: 0.001
Epoch  34 | train: 0.0770 | val: 0.0929 | acc: 96.84% | AUC: 0.997  | LR: 0.001
Epoch  35 | train: 0.0765 | val: 0.0734 | acc: 98.21% | AUC: 0.997  | LR: 0.001
Epoch  36 | train: 0.0812 | val: 0.0713 | acc: 98.14% | AUC: 0.997  | LR: 0.001
Epoch  37 | train: 0.0761 | val: 0.1138 | acc: 95.65% | AUC: 0.996  | LR: 0.0005
Epoch  38 | train: 0.0625 | val: 0.0739 | acc: 97.66% | AUC: 0.997  | LR: 0.0005
Epoch  39 | train: 0.0602 | val: 0.0557 | acc: 98.94% | AUC: 0.997  | LR: 0.0005
Epoch  40 | train: 0.0591 | val: 0.1127 | acc: 95.74% | AUC: 0.997  | LR: 0.0005
Epoch  41 | train: 0.0560 | val: 0.0935 | acc: 96.96% | AUC: 0.996  | LR: 0.0005
  -> ny bästa modell sparad till ../models/cnn_medium.pth
Epoch  42 | train: 0.0600 | val: 0.0511 | acc: 99.03% | AUC: 0.998  | LR: 0.0005
Epoch  43 | train: 0.0598 | val: 0.0595 | acc: 98.57% | AUC: 0.997  | LR: 0.0005
Epoch  44 | train: 0.0506 | val: 0.0623 | acc: 98.51% | AUC: 0.997  | LR: 0.0005
Epoch  45 | train: 0.0529 | val: 0.0861 | acc: 97.47% | AUC: 0.997  | LR: 0.0005
Epoch  46 | train: 0.0523 | val: 0.0723 | acc: 98.17% | AUC: 0.997  | LR: 0.0005
Epoch  47 | train: 0.0476 | val: 0.0748 | acc: 97.93% | AUC: 0.996  | LR: 0.0005
Epoch  48 | train: 0.0472 | val: 0.0568 | acc: 98.66% | AUC: 0.997  | LR: 0.0005
Epoch  49 | train: 0.0457 | val: 0.0562 | acc: 98.78% | AUC: 0.997  | LR: 0.0005
Epoch  50 | train: 0.0492 | val: 0.0550 | acc: 98.90% | AUC: 0.997  | LR: 0.0005
Epoch  51 | train: 0.0481 | val: 0.0602 | acc: 98.51% | AUC: 0.997  | LR: 0.0005
Epoch  52 | train: 0.0479 | val: 0.0615 | acc: 98.54% | AUC: 0.997  | LR: 0.0005
Epoch  53 | train: 0.0447 | val: 0.0532 | acc: 98.90% | AUC: 0.997  | LR: 0.0005
Epoch  54 | train: 0.0470 | val: 0.0562 | acc: 98.90% | AUC: 0.997  | LR: 0.0005
Epoch  55 | train: 0.0468 | val: 0.0779 | acc: 97.84% | AUC: 0.997  | LR: 0.0005
Epoch  56 | train: 0.0420 | val: 0.0619 | acc: 98.42% | AUC: 0.997  | LR: 0.0005
Epoch  57 | train: 0.0388 | val: 0.0628 | acc: 98.54% | AUC: 0.997  | LR: 0.0005
Early stopping efter 58 epoker.
Klar!
Totalt antal utan m-komponent i K-fold poolen: 18848
Totalt antal med m-komponent i K-fold poolen: 2692
Total parameters: 172,130
--- Startar 10-Fold Cross Validation ---

========================================
 FOLD 1/10
========================================
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch   0 | train: 2.8394 | val: 0.5287 | acc: 89.42% | AUC: 0.799  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch   1 | train: 0.4684 | val: 0.4302 | acc: 92.57% | AUC: 0.868  | LR: 0.001
Epoch   2 | train: 0.4877 | val: 0.5099 | acc: 88.63% | AUC: 0.831  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch   3 | train: 0.4460 | val: 0.4344 | acc: 92.48% | AUC: 0.876  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch   4 | train: 0.3891 | val: 0.3949 | acc: 93.13% | AUC: 0.901  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch   5 | train: 0.3536 | val: 0.3506 | acc: 90.62% | AUC: 0.917  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch   6 | train: 0.3186 | val: 0.3328 | acc: 94.01% | AUC: 0.930  | LR: 0.001
Epoch   7 | train: 0.3258 | val: 0.3818 | acc: 85.47% | AUC: 0.917  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch   8 | train: 0.2919 | val: 0.3000 | acc: 93.64% | AUC: 0.940  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch   9 | train: 0.2641 | val: 0.2660 | acc: 92.43% | AUC: 0.952  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  10 | train: 0.2703 | val: 0.2864 | acc: 93.45% | AUC: 0.953  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  11 | train: 0.2298 | val: 0.2320 | acc: 94.80% | AUC: 0.968  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  12 | train: 0.2097 | val: 0.2452 | acc: 95.91% | AUC: 0.969  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  13 | train: 0.1966 | val: 0.2248 | acc: 96.66% | AUC: 0.978  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  14 | train: 0.1938 | val: 0.1888 | acc: 95.82% | AUC: 0.981  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  15 | train: 0.1878 | val: 0.1981 | acc: 95.50% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  16 | train: 0.1682 | val: 0.1710 | acc: 96.89% | AUC: 0.984  | LR: 0.001
Epoch  17 | train: 0.1520 | val: 0.1975 | acc: 97.35% | AUC: 0.984  | LR: 0.001
Epoch  18 | train: 0.1591 | val: 0.2328 | acc: 96.56% | AUC: 0.975  | LR: 0.001
Epoch  19 | train: 0.1539 | val: 0.1804 | acc: 94.01% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  20 | train: 0.1373 | val: 0.1772 | acc: 97.63% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  21 | train: 0.1274 | val: 0.1491 | acc: 96.66% | AUC: 0.987  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  22 | train: 0.1233 | val: 0.1356 | acc: 97.08% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  23 | train: 0.1137 | val: 0.1313 | acc: 97.26% | AUC: 0.990  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  24 | train: 0.1142 | val: 0.1574 | acc: 97.96% | AUC: 0.990  | LR: 0.001
Epoch  25 | train: 0.1114 | val: 0.1495 | acc: 93.92% | AUC: 0.989  | LR: 0.001
Epoch  26 | train: 0.1040 | val: 0.1631 | acc: 97.77% | AUC: 0.989  | LR: 0.001
Epoch  27 | train: 0.0983 | val: 0.1279 | acc: 97.35% | AUC: 0.989  | LR: 0.001
Epoch  28 | train: 0.1056 | val: 0.1387 | acc: 97.40% | AUC: 0.988  | LR: 0.001
Epoch  29 | train: 0.0971 | val: 0.1446 | acc: 97.68% | AUC: 0.989  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  30 | train: 0.0972 | val: 0.1614 | acc: 97.54% | AUC: 0.991  | LR: 0.001
Epoch  31 | train: 0.1025 | val: 0.1301 | acc: 96.10% | AUC: 0.989  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  32 | train: 0.0910 | val: 0.1385 | acc: 94.20% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold1.pth
Epoch  33 | train: 0.0909 | val: 0.1166 | acc: 97.82% | AUC: 0.992  | LR: 0.001
Epoch  34 | train: 0.0897 | val: 0.1235 | acc: 97.40% | AUC: 0.991  | LR: 0.001
Epoch  35 | train: 0.0901 | val: 0.1331 | acc: 97.35% | AUC: 0.988  | LR: 0.001
Epoch  36 | train: 0.0875 | val: 0.1240 | acc: 97.77% | AUC: 0.991  | LR: 0.001
Epoch  37 | train: 0.0823 | val: 0.1231 | acc: 97.59% | AUC: 0.990  | LR: 0.001
Epoch  38 | train: 0.0797 | val: 0.1428 | acc: 97.35% | AUC: 0.989  | LR: 0.001
Epoch  39 | train: 0.0808 | val: 0.1475 | acc: 97.91% | AUC: 0.988  | LR: 0.001
Epoch  40 | train: 0.0819 | val: 0.1355 | acc: 93.69% | AUC: 0.991  | LR: 0.001
Epoch  41 | train: 0.0820 | val: 0.1282 | acc: 95.08% | AUC: 0.992  | LR: 0.001
Epoch  42 | train: 0.0758 | val: 0.1547 | acc: 93.27% | AUC: 0.986  | LR: 0.001
Epoch  43 | train: 0.0745 | val: 0.1306 | acc: 97.68% | AUC: 0.991  | LR: 0.001
Epoch  44 | train: 0.0664 | val: 0.1443 | acc: 97.77% | AUC: 0.991  | LR: 0.001
Epoch  45 | train: 0.0707 | val: 0.1246 | acc: 95.54% | AUC: 0.991  | LR: 0.001
Epoch  46 | train: 0.0690 | val: 0.1252 | acc: 96.19% | AUC: 0.990  | LR: 0.001
Epoch  47 | train: 0.0706 | val: 0.1241 | acc: 97.26% | AUC: 0.991  | LR: 0.001
Epoch  48 | train: 0.0613 | val: 0.1509 | acc: 97.03% | AUC: 0.988  | LR: 0.001
Early stopping efter 49 epoker.
Klar!

Utvärderar bästa modellen för Fold 1...
-> Slutresultat Fold 1: Train Loss: 0.0741 | Val Loss: 0.1166 | AUC: 0.9917

========================================
 FOLD 2/10
========================================
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch   0 | train: 2.3764 | val: 0.5283 | acc: 89.37% | AUC: 0.811  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch   1 | train: 0.4719 | val: 0.4016 | acc: 93.45% | AUC: 0.914  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch   2 | train: 0.3665 | val: 0.2817 | acc: 94.71% | AUC: 0.954  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch   3 | train: 0.3069 | val: 0.2341 | acc: 95.13% | AUC: 0.973  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch   4 | train: 0.2581 | val: 0.2106 | acc: 95.45% | AUC: 0.976  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch   5 | train: 0.2961 | val: 0.1924 | acc: 96.66% | AUC: 0.981  | LR: 0.001
Epoch   6 | train: 0.2308 | val: 0.1980 | acc: 95.87% | AUC: 0.976  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch   7 | train: 0.2135 | val: 0.1580 | acc: 96.70% | AUC: 0.983  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch   8 | train: 0.1785 | val: 0.1572 | acc: 94.75% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch   9 | train: 0.1720 | val: 0.1303 | acc: 96.52% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch  10 | train: 0.1547 | val: 0.1203 | acc: 96.56% | AUC: 0.990  | LR: 0.001
Epoch  11 | train: 0.1628 | val: 0.1388 | acc: 94.94% | AUC: 0.989  | LR: 0.001
Epoch  12 | train: 0.1433 | val: 0.1255 | acc: 97.26% | AUC: 0.989  | LR: 0.001
Epoch  13 | train: 0.1436 | val: 0.1385 | acc: 95.50% | AUC: 0.986  | LR: 0.001
Epoch  14 | train: 0.1360 | val: 0.1254 | acc: 96.19% | AUC: 0.988  | LR: 0.001
Epoch  15 | train: 0.1296 | val: 0.1316 | acc: 95.68% | AUC: 0.989  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold2.pth
Epoch  16 | train: 0.1177 | val: 0.1233 | acc: 95.96% | AUC: 0.991  | LR: 0.001
Epoch  17 | train: 0.1207 | val: 0.1105 | acc: 97.12% | AUC: 0.991  | LR: 0.001
Epoch  18 | train: 0.1133 | val: 0.1326 | acc: 97.73% | AUC: 0.990  | LR: 0.001
Epoch  19 | train: 0.1089 | val: 0.1105 | acc: 97.26% | AUC: 0.990  | LR: 0.001
Epoch  20 | train: 0.1123 | val: 0.1202 | acc: 97.45% | AUC: 0.989  | LR: 0.001
Epoch  21 | train: 0.1028 | val: 0.1174 | acc: 96.56% | AUC: 0.988  | LR: 0.001
Epoch  22 | train: 0.0977 | val: 0.1141 | acc: 96.89% | AUC: 0.989  | LR: 0.001
Epoch  23 | train: 0.0954 | val: 0.1158 | acc: 96.38% | AUC: 0.989  | LR: 0.001
Epoch  24 | train: 0.0956 | val: 0.1139 | acc: 97.17% | AUC: 0.989  | LR: 0.001
Epoch  25 | train: 0.0910 | val: 0.1186 | acc: 97.21% | AUC: 0.988  | LR: 0.001
Epoch  26 | train: 0.0985 | val: 0.1093 | acc: 97.54% | AUC: 0.989  | LR: 0.001
Epoch  27 | train: 0.0940 | val: 0.1218 | acc: 97.49% | AUC: 0.990  | LR: 0.001
Epoch  28 | train: 0.0868 | val: 0.1250 | acc: 95.82% | AUC: 0.986  | LR: 0.001
Epoch  29 | train: 0.0817 | val: 0.1231 | acc: 97.31% | AUC: 0.988  | LR: 0.001
Epoch  30 | train: 0.0859 | val: 0.1200 | acc: 97.08% | AUC: 0.987  | LR: 0.001
Epoch  31 | train: 0.0861 | val: 0.1135 | acc: 96.94% | AUC: 0.990  | LR: 0.001
Epoch  32 | train: 0.0853 | val: 0.1217 | acc: 97.96% | AUC: 0.989  | LR: 0.001
Epoch  33 | train: 0.0743 | val: 0.1256 | acc: 96.98% | AUC: 0.988  | LR: 0.001
Epoch  34 | train: 0.0726 | val: 0.1148 | acc: 97.12% | AUC: 0.988  | LR: 0.001
Epoch  35 | train: 0.0655 | val: 0.1268 | acc: 96.33% | AUC: 0.987  | LR: 0.001
Epoch  36 | train: 0.0645 | val: 0.1267 | acc: 97.35% | AUC: 0.989  | LR: 0.001
Epoch  37 | train: 0.0730 | val: 0.1381 | acc: 94.10% | AUC: 0.989  | LR: 0.001
Epoch  38 | train: 0.0718 | val: 0.1292 | acc: 97.35% | AUC: 0.987  | LR: 0.001
Epoch  39 | train: 0.0723 | val: 0.1239 | acc: 97.08% | AUC: 0.987  | LR: 0.001
Epoch  40 | train: 0.0585 | val: 0.1163 | acc: 96.84% | AUC: 0.988  | LR: 0.001
Epoch  41 | train: 0.0577 | val: 0.1242 | acc: 97.45% | AUC: 0.988  | LR: 0.001
Early stopping efter 42 epoker.
Klar!

Utvärderar bästa modellen för Fold 2...
-> Slutresultat Fold 2: Train Loss: 0.1116 | Val Loss: 0.1233 | AUC: 0.9906

========================================
 FOLD 3/10
========================================
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch   0 | train: 3.7914 | val: 0.5344 | acc: 91.83% | AUC: 0.831  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch   1 | train: 0.4767 | val: 0.4209 | acc: 90.62% | AUC: 0.904  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch   2 | train: 0.3852 | val: 0.3235 | acc: 91.64% | AUC: 0.944  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch   3 | train: 0.3297 | val: 0.2954 | acc: 93.59% | AUC: 0.952  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch   4 | train: 0.2628 | val: 0.2446 | acc: 96.10% | AUC: 0.966  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch   5 | train: 0.2135 | val: 0.2369 | acc: 90.76% | AUC: 0.976  | LR: 0.001
Epoch   6 | train: 0.2156 | val: 0.2202 | acc: 96.70% | AUC: 0.975  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch   7 | train: 0.1769 | val: 0.1977 | acc: 96.28% | AUC: 0.976  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch   8 | train: 0.1816 | val: 0.1776 | acc: 96.80% | AUC: 0.977  | LR: 0.001
Epoch   9 | train: 0.1668 | val: 0.2611 | acc: 97.03% | AUC: 0.975  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch  10 | train: 0.1716 | val: 0.1834 | acc: 93.31% | AUC: 0.982  | LR: 0.001
Epoch  11 | train: 0.1414 | val: 0.1609 | acc: 96.75% | AUC: 0.981  | LR: 0.001
Epoch  12 | train: 0.1428 | val: 0.1748 | acc: 97.31% | AUC: 0.977  | LR: 0.001
Epoch  13 | train: 0.1332 | val: 0.1597 | acc: 95.91% | AUC: 0.981  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch  14 | train: 0.1317 | val: 0.1565 | acc: 95.59% | AUC: 0.983  | LR: 0.001
Epoch  15 | train: 0.1493 | val: 0.1657 | acc: 95.54% | AUC: 0.982  | LR: 0.001
Epoch  16 | train: 0.1412 | val: 0.1782 | acc: 97.26% | AUC: 0.982  | LR: 0.001
Epoch  17 | train: 0.1229 | val: 0.1577 | acc: 96.80% | AUC: 0.982  | LR: 0.001
Epoch  18 | train: 0.1181 | val: 0.1656 | acc: 96.61% | AUC: 0.981  | LR: 0.001
Epoch  19 | train: 0.1219 | val: 0.1626 | acc: 94.84% | AUC: 0.980  | LR: 0.001
Epoch  20 | train: 0.1129 | val: 0.1553 | acc: 95.17% | AUC: 0.981  | LR: 0.001
Epoch  21 | train: 0.1076 | val: 0.1833 | acc: 97.40% | AUC: 0.981  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_medium_fold3.pth
Epoch  22 | train: 0.1077 | val: 0.1503 | acc: 97.07% | AUC: 0.984  | LR: 0.001
Epoch  23 | train: 0.1132 | val: 0.1593 | acc: 96.89% | AUC: 0.981  | LR: 0.001
Epoch  24 | train: 0.1225 | val: 0.1591 | acc: 94.38% | AUC: 0.982  | LR: 0.001
Epoch  25 | train: 0.1038 | val: 0.1615 | acc: 97.17% | AUC: 0.982  | LR: 0.001
Epoch  26 | train: 0.0945 | val: 0.1610 | acc: 97.07% | AUC: 0.982  | LR: 0.001
Epoch  27 | train: 0.0943 | val: 0.1536 | acc: 95.31% | AUC: 0.983  | LR: 0.001
Epoch  28 | train: 0.0908 | val: 0.1625 | acc: 97.12% | AUC: 0.983  | LR: 0.001
Epoch  29 | train: 0.0930 | val: 0.1493 | acc: 96.05% | AUC: 0.981  | LR: 0.001
Epoch  30 | train: 0.0897 | val: 0.1770 | acc: 97.54% | AUC: 0.982  | LR: 0.001
Epoch  31 | train: 0.0848 | val: 0.1594 | acc: 97.35% | AUC: 0.981  | LR: 0.001
Epoch  32 | train: 0.0903 | val: 0.2220 | acc: 97.72% | AUC: 0.981  | LR: 0.001
Epoch  33 | train: 0.0961 | val: 0.1618 | acc: 96.75% | AUC: 0.981  | LR: 0.001
Epoch  34 | train: 0.0852 | val: 0.1703 | acc: 97.49% | AUC: 0.978  | LR: 0.001
Epoch  35 | train: 0.0874 | val: 0.1596 | acc: 97.45% | AUC: 0.982  | LR: 0.001
Epoch  36 | train: 0.0901 | val: 0.1857 | acc: 97.21% | AUC: 0.980  | LR: 0.0005
Epoch  37 | train: 0.0878 | val: 0.1990 | acc: 97.58% | AUC: 0.982  | LR: 0.0005
Epoch  38 | train: 0.0826 | val: 0.1698 | acc: 96.80% | AUC: 0.981  | LR: 0.0005
Epoch  39 | train: 0.0740 | val: 0.1537 | acc: 96.98% | AUC: 0.982  | LR: 0.0005
Epoch  40 | train: 0.0695 | val: 0.1793 | acc: 97.58% | AUC: 0.980  | LR: 0.0005
Epoch  41 | train: 0.0684 | val: 0.2068 | acc: 97.86% | AUC: 0.981  | LR: 0.0005

,fold,train_loss,val_loss,val_accuracy,val_auc,val_spec,val_sens,tn,fp,fn,tp
0,1,0.074083,0.116643,97.818013,0.991745,0.983015,0.944444,1852,32,15,255
1,2,0.111630,0.123342,95.961003,0.990639,0.960722,0.951852,1810,74,13,257
2,3,0.085706,0.150263,97.073850,0.983599,0.980892,0.899628,1848,36,27,242
3,4,0.111073,0.155552,97.539461,0.985807,0.984085,0.914498,1855,30,23,246
4,5,0.085200,0.138537,95.171773,0.991651,0.949072,0.970260,1789,96,8,261
5,6,0.090134,0.086102,97.677659,0.993688,0.981423,0.944238,1849,35,15,254
6,7,0.109958,0.110276,97.770553,0.990914,0.986200,0.918216,1858,26,22,247
7,8,0.101400,0.209552,94.281729,0.974547,0.947396,0.910781,1783,99,24,245
8,9,0.108502,0.312828,94.475395,0.979345,0.945889,0.936803,1783,102,17,252
9,10,0.056400,0.144890,96.470042,0.988654,0.972399,0.910781,1832,52,24,245

In [1]:
import duckdb
from functions.evaluation import evaluate
from networks.cnn_huge import CNNModel
from networks.cnn_network import build_dataloaders


con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


train_rows = df[df['set'] == 'train']
val_rows   = df[df['set'] == 'val']
test_rows  = df[df['set'] == 'test']

drop_indices = train_rows[train_rows['label'] == 0].sample(frac=0.7).index

train_rows = train_rows.drop(drop_indices)
train_rows = train_rows[train_rows['label'].isin([0,1])]
val_rows = val_rows[val_rows['label'].isin([0,1])]

print(f"Antal utan m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 0])}")
print(f"Antal med m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 1])}")

CNN = CNNModel()
cnn_train_dl, cnn_val_dl, _ = build_dataloaders(train_rows, val_rows, val_rows)
CNN.reset_weights()
CNN.retrain(cnn_train_dl,cnn_val_dl,patience=15)

con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


k_fold_rows = df[df['set'].isin(['train','val']) ].copy()
k_fold_rows = k_fold_rows[k_fold_rows['label'].isin([0,1])]
drop_indices = k_fold_rows[k_fold_rows['label'] == 0].sample(frac=0.7).index
k_fold_rows = k_fold_rows.drop(drop_indices)
print(f"Totalt antal utan m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 0])}")
print(f"Totalt antal med m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 1])}")

test_rows  = df[df['set'] == 'test']


CNN = CNNModel()
CNN.retrain_with_k_fold(k_fold_rows)

Antal utan m-komponent i träningsdatan: 17903
Antal med m-komponent i träningsdatan: 2553
Total parameters: 1,505,826
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch   0 | train: 13.9208 | val: 0.3984 | acc: 96.11% | AUC: 0.855  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch   1 | train: 0.4606 | val: 0.2805 | acc: 96.65% | AUC: 0.924  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch   2 | train: 0.3953 | val: 0.2787 | acc: 95.86% | AUC: 0.952  | LR: 0.001
Epoch   3 | train: 0.4017 | val: 0.2602 | acc: 97.54% | AUC: 0.937  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch   4 | train: 0.3402 | val: 0.1731 | acc: 98.60% | AUC: 0.967  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch   5 | train: 0.2900 | val: 0.1565 | acc: 97.87% | AUC: 0.977  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch   6 | train: 0.2418 | val: 0.1367 | acc: 98.81% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch   7 | train: 0.2303 | val: 0.1019 | acc: 98.60% | AUC: 0.993  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch   8 | train: 0.2208 | val: 0.1192 | acc: 97.72% | AUC: 0.993  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch   9 | train: 0.2110 | val: 0.1009 | acc: 98.51% | AUC: 0.994  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch  10 | train: 0.1896 | val: 0.1017 | acc: 98.48% | AUC: 0.994  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch  11 | train: 0.1792 | val: 0.1690 | acc: 94.65% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch  12 | train: 0.1691 | val: 0.1227 | acc: 96.68% | AUC: 0.996  | LR: 0.001
Epoch  13 | train: 0.1578 | val: 0.0779 | acc: 98.90% | AUC: 0.995  | LR: 0.001
Epoch  14 | train: 0.1545 | val: 0.0831 | acc: 98.36% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch  15 | train: 0.1417 | val: 0.0806 | acc: 98.05% | AUC: 0.997  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch  16 | train: 0.1503 | val: 0.1042 | acc: 97.23% | AUC: 0.997  | LR: 0.001
Epoch  17 | train: 0.1422 | val: 0.0711 | acc: 99.12% | AUC: 0.995  | LR: 0.001
Epoch  18 | train: 0.1575 | val: 0.0906 | acc: 97.29% | AUC: 0.996  | LR: 0.001
Epoch  19 | train: 0.1619 | val: 0.1962 | acc: 93.19% | AUC: 0.996  | LR: 0.001
Epoch  20 | train: 0.1383 | val: 0.0928 | acc: 97.41% | AUC: 0.996  | LR: 0.001
Epoch  21 | train: 0.1264 | val: 0.1003 | acc: 97.05% | AUC: 0.997  | LR: 0.001
Epoch  22 | train: 0.1218 | val: 0.1471 | acc: 95.41% | AUC: 0.992  | LR: 0.001
Epoch  23 | train: 0.1240 | val: 0.0608 | acc: 98.72% | AUC: 0.997  | LR: 0.001
Epoch  24 | train: 0.1242 | val: 0.0619 | acc: 99.15% | AUC: 0.996  | LR: 0.001
Epoch  25 | train: 0.1256 | val: 0.0888 | acc: 97.47% | AUC: 0.996  | LR: 0.001
Epoch  26 | train: 0.1103 | val: 0.0747 | acc: 98.14% | AUC: 0.993  | LR: 0.001
Epoch  27 | train: 0.1137 | val: 0.0775 | acc: 98.17% | AUC: 0.997  | LR: 0.001
Epoch  28 | train: 0.1061 | val: 0.0569 | acc: 98.81% | AUC: 0.997  | LR: 0.001
Epoch  29 | train: 0.1017 | val: 0.0848 | acc: 97.29% | AUC: 0.996  | LR: 0.001
Epoch  30 | train: 0.1084 | val: 0.1668 | acc: 93.79% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch  31 | train: 0.1252 | val: 0.0925 | acc: 97.44% | AUC: 0.998  | LR: 0.001
Epoch  32 | train: 0.1036 | val: 0.0845 | acc: 97.78% | AUC: 0.996  | LR: 0.001
Epoch  33 | train: 0.0965 | val: 0.1037 | acc: 97.05% | AUC: 0.996  | LR: 0.001
Epoch  34 | train: 0.0999 | val: 0.1204 | acc: 96.20% | AUC: 0.996  | LR: 0.001
Epoch  35 | train: 0.1023 | val: 0.0549 | acc: 99.12% | AUC: 0.996  | LR: 0.001
Epoch  36 | train: 0.1048 | val: 0.0700 | acc: 98.02% | AUC: 0.997  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch  37 | train: 0.0978 | val: 0.0545 | acc: 98.87% | AUC: 0.998  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch  38 | train: 0.0977 | val: 0.0721 | acc: 97.60% | AUC: 0.998  | LR: 0.0005
Epoch  39 | train: 0.0870 | val: 0.0737 | acc: 97.99% | AUC: 0.997  | LR: 0.0005
Epoch  40 | train: 0.0773 | val: 0.0547 | acc: 98.78% | AUC: 0.998  | LR: 0.0005
Epoch  41 | train: 0.0774 | val: 0.0579 | acc: 98.39% | AUC: 0.998  | LR: 0.0005
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch  42 | train: 0.0748 | val: 0.0626 | acc: 98.17% | AUC: 0.998  | LR: 0.0005
Epoch  43 | train: 0.0762 | val: 0.0670 | acc: 98.02% | AUC: 0.997  | LR: 0.0005
Epoch  44 | train: 0.0730 | val: 0.0608 | acc: 98.69% | AUC: 0.997  | LR: 0.0005
  -> ny bästa modell sparad till ../models/cnn_huge.pth
Epoch  45 | train: 0.0719 | val: 0.0622 | acc: 97.87% | AUC: 0.998  | LR: 0.0005
Epoch  46 | train: 0.0722 | val: 0.0647 | acc: 98.05% | AUC: 0.997  | LR: 0.0005
Epoch  47 | train: 0.0692 | val: 0.1930 | acc: 98.57% | AUC: 0.990  | LR: 0.0005
Epoch  48 | train: 0.0678 | val: 0.1780 | acc: 97.69% | AUC: 0.990  | LR: 0.0005
Epoch  49 | train: 0.0671 | val: 0.1788 | acc: 97.32% | AUC: 0.990  | LR: 0.0005
Epoch  50 | train: 0.0677 | val: 0.2004 | acc: 96.59% | AUC: 0.989  | LR: 0.0005
Epoch  51 | train: 0.0716 | val: 0.0765 | acc: 97.05% | AUC: 0.997  | LR: 0.0005
Epoch  52 | train: 0.0687 | val: 0.1008 | acc: 98.57% | AUC: 0.990  | LR: 0.0005
Early stopping efter 53 epoker.
Klar!
Totalt antal utan m-komponent i K-fold poolen: 18848
Totalt antal med m-komponent i K-fold poolen: 2692
Total parameters: 1,505,826
--- Startar 10-Fold Cross Validation ---

========================================
 FOLD 1/10
========================================
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch   0 | train: 7.5092 | val: 0.5305 | acc: 88.21% | AUC: 0.779  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch   1 | train: 0.4618 | val: 0.4507 | acc: 92.94% | AUC: 0.880  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch   2 | train: 0.3961 | val: 0.3814 | acc: 92.99% | AUC: 0.911  | LR: 0.001
Epoch   3 | train: 0.3846 | val: 0.3789 | acc: 87.65% | AUC: 0.898  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch   4 | train: 0.3513 | val: 0.3361 | acc: 94.43% | AUC: 0.929  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch   5 | train: 0.2841 | val: 0.2617 | acc: 94.52% | AUC: 0.950  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch   6 | train: 0.2252 | val: 0.2385 | acc: 96.33% | AUC: 0.967  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch   7 | train: 0.2100 | val: 0.2128 | acc: 96.80% | AUC: 0.976  | LR: 0.001
Epoch   8 | train: 0.1951 | val: 0.3103 | acc: 82.50% | AUC: 0.970  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch   9 | train: 0.1897 | val: 0.1511 | acc: 95.91% | AUC: 0.984  | LR: 0.001
Epoch  10 | train: 0.1665 | val: 0.1711 | acc: 93.55% | AUC: 0.983  | LR: 0.001
Epoch  11 | train: 0.1362 | val: 0.1485 | acc: 96.56% | AUC: 0.983  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch  12 | train: 0.1346 | val: 0.1339 | acc: 97.03% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch  13 | train: 0.1305 | val: 0.1326 | acc: 97.45% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch  14 | train: 0.1219 | val: 0.1367 | acc: 97.82% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch  15 | train: 0.1157 | val: 0.1260 | acc: 97.77% | AUC: 0.989  | LR: 0.001
Epoch  16 | train: 0.1125 | val: 0.1248 | acc: 96.43% | AUC: 0.988  | LR: 0.001
Epoch  17 | train: 0.1103 | val: 0.1192 | acc: 96.80% | AUC: 0.989  | LR: 0.001
Epoch  18 | train: 0.1083 | val: 0.1265 | acc: 96.52% | AUC: 0.987  | LR: 0.001
Epoch  19 | train: 0.1064 | val: 0.1253 | acc: 97.12% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch  20 | train: 0.1088 | val: 0.1311 | acc: 97.91% | AUC: 0.989  | LR: 0.001
Epoch  21 | train: 0.1002 | val: 0.1162 | acc: 97.68% | AUC: 0.989  | LR: 0.001
Epoch  22 | train: 0.0961 | val: 0.1818 | acc: 98.00% | AUC: 0.989  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch  23 | train: 0.0911 | val: 0.1299 | acc: 97.91% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold1.pth
Epoch  24 | train: 0.0876 | val: 0.1108 | acc: 96.01% | AUC: 0.991  | LR: 0.001
Epoch  25 | train: 0.0896 | val: 0.1164 | acc: 97.54% | AUC: 0.988  | LR: 0.001
Epoch  26 | train: 0.0813 | val: 0.1240 | acc: 98.10% | AUC: 0.989  | LR: 0.001
Epoch  27 | train: 0.0782 | val: 0.1177 | acc: 97.86% | AUC: 0.989  | LR: 0.001
Epoch  28 | train: 0.0723 | val: 0.1311 | acc: 98.05% | AUC: 0.989  | LR: 0.001
Epoch  29 | train: 0.0763 | val: 0.1151 | acc: 98.14% | AUC: 0.990  | LR: 0.001
Epoch  30 | train: 0.0685 | val: 0.1113 | acc: 96.33% | AUC: 0.989  | LR: 0.001
Epoch  31 | train: 0.0666 | val: 0.1365 | acc: 97.91% | AUC: 0.990  | LR: 0.001
Epoch  32 | train: 0.0632 | val: 0.1154 | acc: 97.73% | AUC: 0.990  | LR: 0.001
Epoch  33 | train: 0.0642 | val: 0.1353 | acc: 97.03% | AUC: 0.989  | LR: 0.001
Epoch  34 | train: 0.0584 | val: 0.1200 | acc: 97.40% | AUC: 0.989  | LR: 0.001
Epoch  35 | train: 0.0621 | val: 0.1305 | acc: 97.91% | AUC: 0.989  | LR: 0.001
Epoch  36 | train: 0.0553 | val: 0.1361 | acc: 97.03% | AUC: 0.987  | LR: 0.001
Epoch  37 | train: 0.0511 | val: 0.1459 | acc: 97.73% | AUC: 0.988  | LR: 0.001
Epoch  38 | train: 0.0492 | val: 0.1288 | acc: 97.08% | AUC: 0.989  | LR: 0.001
Epoch  39 | train: 0.0461 | val: 0.1447 | acc: 97.54% | AUC: 0.988  | LR: 0.001
Early stopping efter 40 epoker.
Klar!

Utvärderar bästa modellen för Fold 1...
-> Slutresultat Fold 1: Train Loss: 0.0849 | Val Loss: 0.1108 | AUC: 0.9908

========================================
 FOLD 2/10
========================================
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch   0 | train: 9.2307 | val: 0.5614 | acc: 91.55% | AUC: 0.795  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch   1 | train: 0.4804 | val: 0.3772 | acc: 90.11% | AUC: 0.920  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch   2 | train: 0.3643 | val: 0.3270 | acc: 88.95% | AUC: 0.947  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch   3 | train: 0.3049 | val: 0.2313 | acc: 95.45% | AUC: 0.972  | LR: 0.001
Epoch   4 | train: 0.2896 | val: 0.2602 | acc: 92.71% | AUC: 0.960  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch   5 | train: 0.2411 | val: 0.1931 | acc: 94.24% | AUC: 0.978  | LR: 0.001
Epoch   6 | train: 0.2358 | val: 0.1986 | acc: 95.96% | AUC: 0.973  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch   7 | train: 0.2024 | val: 0.1435 | acc: 96.42% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch   8 | train: 0.2084 | val: 0.1531 | acc: 95.26% | AUC: 0.984  | LR: 0.001
Epoch   9 | train: 0.1869 | val: 0.1788 | acc: 96.80% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch  10 | train: 0.1642 | val: 0.1331 | acc: 95.63% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch  11 | train: 0.1474 | val: 0.1131 | acc: 96.61% | AUC: 0.991  | LR: 0.001
Epoch  12 | train: 0.1419 | val: 0.1078 | acc: 96.98% | AUC: 0.990  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch  13 | train: 0.1412 | val: 0.1558 | acc: 93.03% | AUC: 0.992  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch  14 | train: 0.1382 | val: 0.1121 | acc: 96.52% | AUC: 0.993  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch  15 | train: 0.1381 | val: 0.0997 | acc: 97.54% | AUC: 0.993  | LR: 0.001
Epoch  16 | train: 0.1294 | val: 0.1064 | acc: 96.28% | AUC: 0.992  | LR: 0.001
Epoch  17 | train: 0.1183 | val: 0.1064 | acc: 98.00% | AUC: 0.992  | LR: 0.001
Epoch  18 | train: 0.1144 | val: 0.1092 | acc: 98.10% | AUC: 0.992  | LR: 0.001
Epoch  19 | train: 0.1273 | val: 0.0982 | acc: 97.68% | AUC: 0.992  | LR: 0.001
Epoch  20 | train: 0.1177 | val: 0.1055 | acc: 97.49% | AUC: 0.991  | LR: 0.001
Epoch  21 | train: 0.1157 | val: 0.0999 | acc: 97.26% | AUC: 0.992  | LR: 0.001
Epoch  22 | train: 0.1009 | val: 0.1039 | acc: 96.33% | AUC: 0.993  | LR: 0.001
Epoch  23 | train: 0.0991 | val: 0.0952 | acc: 96.93% | AUC: 0.992  | LR: 0.001
Epoch  24 | train: 0.0989 | val: 0.1108 | acc: 95.73% | AUC: 0.991  | LR: 0.001
Epoch  25 | train: 0.1026 | val: 0.0949 | acc: 96.98% | AUC: 0.992  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold2.pth
Epoch  26 | train: 0.0925 | val: 0.0972 | acc: 96.70% | AUC: 0.993  | LR: 0.001
Epoch  27 | train: 0.0916 | val: 0.0960 | acc: 97.26% | AUC: 0.992  | LR: 0.001
Epoch  28 | train: 0.0901 | val: 0.1361 | acc: 98.05% | AUC: 0.990  | LR: 0.001
Epoch  29 | train: 0.0972 | val: 0.1205 | acc: 97.82% | AUC: 0.990  | LR: 0.001
Epoch  30 | train: 0.0988 | val: 0.1570 | acc: 98.14% | AUC: 0.987  | LR: 0.001
Epoch  31 | train: 0.0841 | val: 0.1034 | acc: 96.84% | AUC: 0.990  | LR: 0.001
Epoch  32 | train: 0.0869 | val: 0.1008 | acc: 96.38% | AUC: 0.991  | LR: 0.001
Epoch  33 | train: 0.0778 | val: 0.1123 | acc: 97.96% | AUC: 0.987  | LR: 0.001
Epoch  34 | train: 0.0815 | val: 0.0976 | acc: 97.26% | AUC: 0.992  | LR: 0.001
Epoch  35 | train: 0.0801 | val: 0.1028 | acc: 96.66% | AUC: 0.991  | LR: 0.001
Epoch  36 | train: 0.0735 | val: 0.0952 | acc: 97.58% | AUC: 0.992  | LR: 0.001
Epoch  37 | train: 0.0662 | val: 0.1115 | acc: 95.26% | AUC: 0.991  | LR: 0.001
Epoch  38 | train: 0.0689 | val: 0.1104 | acc: 95.36% | AUC: 0.992  | LR: 0.001
Epoch  39 | train: 0.0660 | val: 0.1195 | acc: 98.14% | AUC: 0.990  | LR: 0.001
Epoch  40 | train: 0.0622 | val: 0.1036 | acc: 96.93% | AUC: 0.991  | LR: 0.001
Early stopping efter 41 epoker.
Klar!

Utvärderar bästa modellen för Fold 2...
-> Slutresultat Fold 2: Train Loss: 0.0800 | Val Loss: 0.0972 | AUC: 0.9931

========================================
 FOLD 3/10
========================================
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch   0 | train: 9.0904 | val: 0.5025 | acc: 90.57% | AUC: 0.831  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch   1 | train: 0.4590 | val: 0.4042 | acc: 90.57% | AUC: 0.907  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch   2 | train: 0.3829 | val: 0.4198 | acc: 74.83% | AUC: 0.933  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch   3 | train: 0.3344 | val: 0.2642 | acc: 93.22% | AUC: 0.957  | LR: 0.001
Epoch   4 | train: 0.3442 | val: 0.3513 | acc: 90.94% | AUC: 0.921  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch   5 | train: 0.3068 | val: 0.2648 | acc: 94.43% | AUC: 0.958  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch   6 | train: 0.2614 | val: 0.2454 | acc: 90.90% | AUC: 0.970  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch   7 | train: 0.2483 | val: 0.2267 | acc: 96.14% | AUC: 0.971  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch   8 | train: 0.2084 | val: 0.2299 | acc: 91.36% | AUC: 0.976  | LR: 0.001
Epoch   9 | train: 0.2112 | val: 0.2567 | acc: 95.87% | AUC: 0.967  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch  10 | train: 0.1853 | val: 0.1887 | acc: 95.77% | AUC: 0.978  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch  11 | train: 0.1629 | val: 0.1681 | acc: 96.01% | AUC: 0.982  | LR: 0.001
Epoch  12 | train: 0.1435 | val: 0.1916 | acc: 97.03% | AUC: 0.981  | LR: 0.001
Epoch  13 | train: 0.1360 | val: 0.1801 | acc: 96.80% | AUC: 0.981  | LR: 0.001
Epoch  14 | train: 0.1821 | val: 0.2072 | acc: 95.49% | AUC: 0.972  | LR: 0.001
Epoch  15 | train: 0.1500 | val: 0.1772 | acc: 97.26% | AUC: 0.981  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch  16 | train: 0.1334 | val: 0.1595 | acc: 96.10% | AUC: 0.983  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch  17 | train: 0.1260 | val: 0.1574 | acc: 96.61% | AUC: 0.984  | LR: 0.001
Epoch  18 | train: 0.1101 | val: 0.1662 | acc: 96.80% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch  19 | train: 0.1099 | val: 0.2025 | acc: 97.45% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch  20 | train: 0.1034 | val: 0.1537 | acc: 95.73% | AUC: 0.986  | LR: 0.001
Epoch  21 | train: 0.0957 | val: 0.1569 | acc: 96.84% | AUC: 0.985  | LR: 0.001
Epoch  22 | train: 0.0946 | val: 0.1666 | acc: 97.17% | AUC: 0.985  | LR: 0.001
Epoch  23 | train: 0.0897 | val: 0.1818 | acc: 97.58% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold3.pth
Epoch  24 | train: 0.0858 | val: 0.1417 | acc: 96.61% | AUC: 0.987  | LR: 0.001
Epoch  25 | train: 0.0785 | val: 0.1490 | acc: 94.57% | AUC: 0.985  | LR: 0.001
Epoch  26 | train: 0.0871 | val: 0.1501 | acc: 97.07% | AUC: 0.987  | LR: 0.001
Epoch  27 | train: 0.0921 | val: 0.1980 | acc: 97.45% | AUC: 0.984  | LR: 0.001
Epoch  28 | train: 0.0747 | val: 0.1620 | acc: 97.31% | AUC: 0.985  | LR: 0.001
Epoch  29 | train: 0.0712 | val: 0.1781 | acc: 97.26% | AUC: 0.984  | LR: 0.001
Epoch  30 | train: 0.0630 | val: 0.1405 | acc: 96.66% | AUC: 0.987  | LR: 0.001
Epoch  31 | train: 0.0606 | val: 0.1833 | acc: 97.72% | AUC: 0.986  | LR: 0.001
Epoch  32 | train: 0.0651 | val: 0.2021 | acc: 97.54% | AUC: 0.984  | LR: 0.001
Epoch  33 | train: 0.0676 | val: 0.1800 | acc: 97.17% | AUC: 0.985  | LR: 0.001
Epoch  34 | train: 0.1009 | val: 0.1828 | acc: 97.31% | AUC: 0.983  | LR: 0.001
Epoch  35 | train: 0.0753 | val: 0.1591 | acc: 96.38% | AUC: 0.982  | LR: 0.001
Epoch  36 | train: 0.0562 | val: 0.1894 | acc: 97.40% | AUC: 0.984  | LR: 0.001
Epoch  37 | train: 0.0566 | val: 0.1979 | acc: 97.26% | AUC: 0.981  | LR: 0.001
Epoch  38 | train: 0.0551 | val: 0.1455 | acc: 95.91% | AUC: 0.984  | LR: 0.001
Epoch  39 | train: 0.0510 | val: 0.1990 | acc: 97.45% | AUC: 0.982  | LR: 0.001
Epoch  40 | train: 0.0456 | val: 0.2059 | acc: 97.40% | AUC: 0.982  | LR: 0.001
Epoch  41 | train: 0.0414 | val: 0.2585 | acc: 97.26% | AUC: 0.982  | LR: 0.001
Epoch  42 | train: 0.0469 | val: 0.2277 | acc: 97.72% | AUC: 0.979  | LR: 0.001
Epoch  43 | train: 0.0447 | val: 0.2123 | acc: 97.68% | AUC: 0.980  | LR: 0.001
Epoch  44 | train: 0.0417 | val: 0.2264 | acc: 97.49% | AUC: 0.981  | LR: 0.001
Epoch  45 | train: 0.0361 | val: 0.2075 | acc: 97.26% | AUC: 0.980  | LR: 0.001
Early stopping efter 46 epoker.
Klar!

Utvärderar bästa modellen för Fold 3...
-> Slutresultat Fold 3: Train Loss: 0.0765 | Val Loss: 0.1417 | AUC: 0.9872

========================================
 FOLD 4/10
========================================
  -> ny bästa modell sparad till ../models/cnn_huge_fold4.pth
Epoch   0 | train: 12.4535 | val: 0.5718 | acc: 89.40% | AUC: 0.784  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold4.pth
Epoch   1 | train: 0.4881 | val: 0.4281 | acc: 87.12% | AUC: 0.892  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold4.pth
Epoch   2 | train: 0.4238 | val: 0.4310 | acc: 93.77% | AUC: 0.916  | LR: 0.001
Epoch   3 | train: 0.4319 | val: 0.3883 | acc: 93.58% | AUC: 0.914  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_huge_fold4.pth
Epoch   4 | train: 0.3468 | val: 0.3091 | acc: 95.35% | AUC: 0.940  | LR: 0.001

,fold,train_loss,val_loss,val_accuracy,val_auc,val_spec,val_sens,tn,fp,fn,tp
0,1,0.084865,0.110832,96.007428,0.990790,0.960191,0.959259,1809,75,11,259
1,2,0.080029,0.097213,96.702276,0.993102,0.967605,0.962963,1822,61,10,260
2,3,0.076526,0.141724,96.609382,0.987222,0.972399,0.921933,1832,52,21,248
3,4,0.088791,0.153521,96.048350,0.985120,0.961743,0.951673,1810,72,13,256
4,5,0.105475,0.168884,95.864312,0.985803,0.960170,0.947955,1808,75,14,255
5,6,0.101697,0.104931,96.703807,0.988960,0.970292,0.944238,1829,56,15,254
6,7,0.104429,0.132560,94.377323,0.987434,0.940520,0.966543,1771,112,9,260
7,8,0.071663,0.181953,97.539461,0.985947,0.985676,0.903346,1858,27,26,243
8,9,0.125679,0.341175,94.661096,0.977299,0.949072,0.929368,1789,96,19,250
9,10,0.722958,0.671676,88.759870,0.872115,1.000000,0.100372,1884,0,242,27