In [1]:
import duckdb
from networks.cnn_no_local_pooling import CNNModel
from networks.cnn_network import build_dataloaders


con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


train_rows = df[df['set'] == 'train']
val_rows   = df[df['set'] == 'val']
test_rows  = df[df['set'] == 'test']

drop_indices = train_rows[train_rows['label'] == 0].sample(frac=0.7).index

train_rows = train_rows.drop(drop_indices)
train_rows = train_rows[train_rows['label'].isin([0,1])]
val_rows = val_rows[val_rows['label'].isin([0,1])]

print(f"Antal utan m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 0])}")
print(f"Antal med m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 1])}")

CNN = CNNModel()
cnn_train_dl, cnn_val_dl, _ = build_dataloaders(train_rows, val_rows, val_rows)
CNN.reset_weights()
CNN.retrain(cnn_train_dl,cnn_val_dl,patience=15)

con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


k_fold_rows = df[df['set'].isin(['train','val']) ].copy()
k_fold_rows = k_fold_rows[k_fold_rows['label'].isin([0,1])]
drop_indices = k_fold_rows[k_fold_rows['label'] == 0].sample(frac=0.7).index
k_fold_rows = k_fold_rows.drop(drop_indices)
print(f"Totalt antal utan m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 0])}")
print(f"Totalt antal med m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 1])}")

test_rows  = df[df['set'] == 'test']


CNN = CNNModel()
CNN.retrain_with_k_fold(k_fold_rows)

Antal utan m-komponent i träningsdatan: 17903
Antal med m-komponent i träningsdatan: 2553
Total parameters: 632,930
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch   0 | train: 2.8223 | val: 0.7526 | acc: 4.23% | AUC: 0.500  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch   1 | train: 0.6979 | val: 0.7377 | acc: 4.23% | AUC: 0.504  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch   2 | train: 0.6960 | val: 0.7177 | acc: 4.23% | AUC: 0.532  | LR: 0.001
Epoch   3 | train: 0.6762 | val: 0.7058 | acc: 4.23% | AUC: 0.511  | LR: 0.001
Epoch   4 | train: 0.6902 | val: 0.6939 | acc: 4.23% | AUC: 0.511  | LR: 0.001
Epoch   5 | train: 0.6825 | val: 0.6802 | acc: 95.95% | AUC: 0.522  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch   6 | train: 0.6584 | val: 0.6507 | acc: 90.20% | AUC: 0.679  | LR: 0.001
Epoch   7 | train: 0.6256 | val: 0.6152 | acc: 96.96% | AUC: 0.668  | LR: 0.001
Epoch   8 | train: 0.6153 | val: 0.6181 | acc: 96.47% | AUC: 0.583  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch   9 | train: 0.5914 | val: 0.5847 | acc: 89.87% | AUC: 0.764  | LR: 0.001
Epoch  10 | train: 0.6116 | val: 0.6017 | acc: 96.20% | AUC: 0.550  | LR: 0.001
Epoch  11 | train: 0.6254 | val: 0.5813 | acc: 88.50% | AUC: 0.726  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  12 | train: 0.5722 | val: 0.5456 | acc: 89.84% | AUC: 0.791  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  13 | train: 0.5267 | val: 0.5102 | acc: 93.15% | AUC: 0.819  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  14 | train: 0.5029 | val: 0.5126 | acc: 88.07% | AUC: 0.842  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  15 | train: 0.4889 | val: 0.4729 | acc: 92.42% | AUC: 0.916  | LR: 0.001
Epoch  16 | train: 0.4651 | val: 0.4544 | acc: 92.49% | AUC: 0.877  | LR: 0.001
Epoch  17 | train: 0.4415 | val: 0.4140 | acc: 96.26% | AUC: 0.908  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  18 | train: 0.4147 | val: 0.4083 | acc: 93.49% | AUC: 0.922  | LR: 0.001
Epoch  19 | train: 0.3961 | val: 0.3916 | acc: 95.92% | AUC: 0.866  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  20 | train: 0.4178 | val: 0.4131 | acc: 90.51% | AUC: 0.927  | LR: 0.001
Epoch  21 | train: 0.3972 | val: 0.3495 | acc: 97.57% | AUC: 0.923  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  22 | train: 0.3675 | val: 0.3352 | acc: 96.74% | AUC: 0.945  | LR: 0.001
Epoch  23 | train: 0.3557 | val: 0.3250 | acc: 98.30% | AUC: 0.905  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  24 | train: 0.3472 | val: 0.3077 | acc: 97.93% | AUC: 0.951  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  25 | train: 0.3323 | val: 0.4855 | acc: 76.18% | AUC: 0.978  | LR: 0.001
Epoch  26 | train: 0.3243 | val: 0.2609 | acc: 96.90% | AUC: 0.977  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  27 | train: 0.2717 | val: 0.1921 | acc: 96.56% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  28 | train: 0.2404 | val: 0.2692 | acc: 92.36% | AUC: 0.993  | LR: 0.001
Epoch  29 | train: 0.2078 | val: 0.1854 | acc: 95.74% | AUC: 0.989  | LR: 0.001
Epoch  30 | train: 0.1912 | val: 0.1651 | acc: 97.20% | AUC: 0.993  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  31 | train: 0.1779 | val: 0.1311 | acc: 97.51% | AUC: 0.993  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  32 | train: 0.1763 | val: 0.1866 | acc: 94.98% | AUC: 0.994  | LR: 0.001
Epoch  33 | train: 0.1568 | val: 0.1044 | acc: 98.08% | AUC: 0.994  | LR: 0.001
Epoch  34 | train: 0.1593 | val: 0.1091 | acc: 98.94% | AUC: 0.992  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  35 | train: 0.1543 | val: 0.1268 | acc: 96.78% | AUC: 0.995  | LR: 0.001
Epoch  36 | train: 0.1471 | val: 0.0923 | acc: 98.36% | AUC: 0.995  | LR: 0.001
Epoch  37 | train: 0.1345 | val: 0.1294 | acc: 97.47% | AUC: 0.995  | LR: 0.001
Epoch  38 | train: 0.1351 | val: 0.0936 | acc: 98.54% | AUC: 0.995  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling.pth
Epoch  39 | train: 0.1257 | val: 0.0935 | acc: 98.27% | AUC: 0.996  | LR: 0.001
Epoch  40 | train: 0.1239 | val: 0.0807 | acc: 98.60% | AUC: 0.995  | LR: 0.001
Epoch  41 | train: 0.1154 | val: 0.1322 | acc: 97.35% | AUC: 0.988  | LR: 0.001
Epoch  42 | train: 0.1163 | val: 0.1482 | acc: 96.44% | AUC: 0.988  | LR: 0.001
Epoch  43 | train: 0.1128 | val: 0.1687 | acc: 96.59% | AUC: 0.988  | LR: 0.001
Epoch  44 | train: 0.1064 | val: 0.0941 | acc: 97.81% | AUC: 0.995  | LR: 0.001
Epoch  45 | train: 0.1018 | val: 0.0947 | acc: 98.63% | AUC: 0.988  | LR: 0.001
Epoch  46 | train: 0.0984 | val: 0.1250 | acc: 97.47% | AUC: 0.988  | LR: 0.001
Epoch  47 | train: 0.1015 | val: 0.1156 | acc: 98.36% | AUC: 0.988  | LR: 0.001
Epoch  48 | train: 0.1089 | val: 0.1308 | acc: 96.78% | AUC: 0.989  | LR: 0.001
Epoch  49 | train: 0.0951 | val: 0.1748 | acc: 95.77% | AUC: 0.989  | LR: 0.001
Epoch  50 | train: 0.0948 | val: 0.1737 | acc: 97.72% | AUC: 0.989  | LR: 0.001
Epoch  51 | train: 0.0917 | val: 0.2676 | acc: 96.20% | AUC: 0.988  | LR: 0.001
Epoch  52 | train: 0.0923 | val: 0.2822 | acc: 97.20% | AUC: 0.988  | LR: 0.001
Epoch  53 | train: 0.0896 | val: 0.1431 | acc: 96.87% | AUC: 0.988  | LR: 0.001
Epoch  54 | train: 0.0897 | val: 0.1411 | acc: 98.02% | AUC: 0.989  | LR: 0.001
Epoch  55 | train: 0.0837 | val: 0.1642 | acc: 97.23% | AUC: 0.988  | LR: 0.001
Early stopping efter 56 epoker.
Klar!
Totalt antal utan m-komponent i K-fold poolen: 18848
Totalt antal med m-komponent i K-fold poolen: 2692
Total parameters: 632,930
--- Startar 10-Fold Cross Validation ---

========================================
 FOLD 1/10
========================================
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch   0 | train: 6.2863 | val: 0.6431 | acc: 83.80% | AUC: 0.661  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch   1 | train: 0.5694 | val: 0.5011 | acc: 85.24% | AUC: 0.828  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch   2 | train: 0.5157 | val: 0.4750 | acc: 91.18% | AUC: 0.865  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch   3 | train: 0.4003 | val: 0.6062 | acc: 42.76% | AUC: 0.900  | LR: 0.001
Epoch   4 | train: 0.4526 | val: 0.4226 | acc: 88.67% | AUC: 0.894  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch   5 | train: 0.3874 | val: 0.3913 | acc: 86.91% | AUC: 0.917  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch   6 | train: 0.3464 | val: 0.3334 | acc: 91.92% | AUC: 0.933  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch   7 | train: 0.3454 | val: 0.3592 | acc: 93.59% | AUC: 0.935  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch   8 | train: 0.2994 | val: 0.3518 | acc: 82.92% | AUC: 0.940  | LR: 0.001
Epoch   9 | train: 0.2947 | val: 0.3809 | acc: 90.25% | AUC: 0.901  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch  10 | train: 0.3089 | val: 0.2987 | acc: 93.64% | AUC: 0.948  | LR: 0.001
Epoch  11 | train: 0.2439 | val: 0.3872 | acc: 94.61% | AUC: 0.923  | LR: 0.001
Epoch  12 | train: 0.3562 | val: 0.3272 | acc: 91.74% | AUC: 0.933  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch  13 | train: 0.2483 | val: 0.2337 | acc: 94.71% | AUC: 0.970  | LR: 0.001
Epoch  14 | train: 0.2062 | val: 0.2486 | acc: 95.17% | AUC: 0.964  | LR: 0.001
Epoch  15 | train: 0.1918 | val: 0.2277 | acc: 94.52% | AUC: 0.968  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch  16 | train: 0.1667 | val: 0.2216 | acc: 93.31% | AUC: 0.971  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch  17 | train: 0.1710 | val: 0.2208 | acc: 95.64% | AUC: 0.977  | LR: 0.001
Epoch  18 | train: 0.1671 | val: 0.2219 | acc: 95.64% | AUC: 0.972  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold1.pth
Epoch  19 | train: 0.1535 | val: 0.1990 | acc: 94.71% | AUC: 0.977  | LR: 0.001
Epoch  20 | train: 0.1472 | val: 0.2074 | acc: 93.83% | AUC: 0.974  | LR: 0.001
Epoch  21 | train: 0.1380 | val: 0.2150 | acc: 94.80% | AUC: 0.974  | LR: 0.001
Epoch  22 | train: 0.1412 | val: 0.2091 | acc: 93.08% | AUC: 0.975  | LR: 0.001
Epoch  23 | train: 0.1375 | val: 0.2137 | acc: 94.75% | AUC: 0.973  | LR: 0.001
Epoch  24 | train: 0.1301 | val: 0.2325 | acc: 96.38% | AUC: 0.976  | LR: 0.001
Epoch  25 | train: 0.1310 | val: 0.2369 | acc: 94.80% | AUC: 0.966  | LR: 0.001
Epoch  26 | train: 0.1285 | val: 0.2502 | acc: 95.91% | AUC: 0.971  | LR: 0.001
Epoch  27 | train: 0.1249 | val: 0.2090 | acc: 94.38% | AUC: 0.974  | LR: 0.001
Epoch  28 | train: 0.1156 | val: 0.3218 | acc: 96.05% | AUC: 0.971  | LR: 0.001
Epoch  29 | train: 0.1263 | val: 0.2144 | acc: 94.48% | AUC: 0.973  | LR: 0.001
Epoch  30 | train: 0.1171 | val: 0.2131 | acc: 93.50% | AUC: 0.974  | LR: 0.001
Epoch  31 | train: 0.1079 | val: 0.2999 | acc: 96.43% | AUC: 0.971  | LR: 0.001
Epoch  32 | train: 0.1013 | val: 0.2207 | acc: 95.73% | AUC: 0.974  | LR: 0.001
Epoch  33 | train: 0.1016 | val: 0.2542 | acc: 96.29% | AUC: 0.976  | LR: 0.001
Epoch  34 | train: 0.1094 | val: 0.2305 | acc: 96.19% | AUC: 0.977  | LR: 0.001
Early stopping efter 35 epoker.
Klar!

Utvärderar bästa modellen för Fold 1...
-> Slutresultat Fold 1: Train Loss: 0.1219 | Val Loss: 0.1990 | AUC: 0.9771

========================================
 FOLD 2/10
========================================
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch   0 | train: 6.1216 | val: 0.7051 | acc: 89.14% | AUC: 0.705  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch   1 | train: 0.5741 | val: 0.4895 | acc: 88.39% | AUC: 0.855  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch   2 | train: 0.4927 | val: 0.4512 | acc: 91.64% | AUC: 0.870  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch   3 | train: 0.3953 | val: 0.3812 | acc: 83.89% | AUC: 0.920  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch   4 | train: 0.3299 | val: 0.3307 | acc: 94.01% | AUC: 0.923  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch   5 | train: 0.2800 | val: 0.3371 | acc: 95.22% | AUC: 0.943  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch   6 | train: 0.2807 | val: 0.2948 | acc: 90.95% | AUC: 0.944  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch   7 | train: 0.2590 | val: 0.2951 | acc: 93.92% | AUC: 0.944  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch   8 | train: 0.2288 | val: 0.3387 | acc: 81.75% | AUC: 0.948  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch   9 | train: 0.2273 | val: 0.2296 | acc: 95.91% | AUC: 0.964  | LR: 0.001
Epoch  10 | train: 0.1928 | val: 0.2352 | acc: 91.97% | AUC: 0.963  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  11 | train: 0.1859 | val: 0.1938 | acc: 94.06% | AUC: 0.972  | LR: 0.001
Epoch  12 | train: 0.1719 | val: 0.1924 | acc: 96.24% | AUC: 0.972  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  13 | train: 0.1629 | val: 0.2070 | acc: 96.43% | AUC: 0.975  | LR: 0.001
Epoch  14 | train: 0.1625 | val: 0.2638 | acc: 96.10% | AUC: 0.968  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  15 | train: 0.1644 | val: 0.1781 | acc: 94.99% | AUC: 0.976  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  16 | train: 0.1510 | val: 0.1938 | acc: 96.43% | AUC: 0.976  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  17 | train: 0.1466 | val: 0.1682 | acc: 94.34% | AUC: 0.980  | LR: 0.001
Epoch  18 | train: 0.1534 | val: 0.1922 | acc: 93.08% | AUC: 0.975  | LR: 0.001
Epoch  19 | train: 0.1403 | val: 0.1788 | acc: 96.61% | AUC: 0.976  | LR: 0.001
Epoch  20 | train: 0.1334 | val: 0.1643 | acc: 94.20% | AUC: 0.980  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  21 | train: 0.1246 | val: 0.1593 | acc: 95.73% | AUC: 0.981  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  22 | train: 0.1213 | val: 0.1554 | acc: 96.19% | AUC: 0.983  | LR: 0.001
Epoch  23 | train: 0.1190 | val: 0.1567 | acc: 94.34% | AUC: 0.983  | LR: 0.001
Epoch  24 | train: 0.1166 | val: 0.1658 | acc: 96.05% | AUC: 0.981  | LR: 0.001
Epoch  25 | train: 0.1151 | val: 0.1570 | acc: 95.03% | AUC: 0.981  | LR: 0.001
Epoch  26 | train: 0.1212 | val: 0.1826 | acc: 96.80% | AUC: 0.977  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  27 | train: 0.1227 | val: 0.1600 | acc: 93.78% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  28 | train: 0.1133 | val: 0.1508 | acc: 96.70% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  29 | train: 0.1074 | val: 0.1441 | acc: 95.87% | AUC: 0.984  | LR: 0.001
Epoch  30 | train: 0.1053 | val: 0.1580 | acc: 96.98% | AUC: 0.984  | LR: 0.001
Epoch  31 | train: 0.1092 | val: 0.1495 | acc: 96.75% | AUC: 0.984  | LR: 0.001
Epoch  32 | train: 0.1034 | val: 0.1549 | acc: 96.33% | AUC: 0.982  | LR: 0.001
Epoch  33 | train: 0.1008 | val: 0.2085 | acc: 97.35% | AUC: 0.980  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  34 | train: 0.1082 | val: 0.1433 | acc: 95.45% | AUC: 0.985  | LR: 0.001
Epoch  35 | train: 0.1008 | val: 0.1533 | acc: 93.78% | AUC: 0.983  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  36 | train: 0.0961 | val: 0.1414 | acc: 95.59% | AUC: 0.986  | LR: 0.001
Epoch  37 | train: 0.0979 | val: 0.1532 | acc: 96.80% | AUC: 0.984  | LR: 0.001
Epoch  38 | train: 0.0884 | val: 0.1490 | acc: 97.35% | AUC: 0.985  | LR: 0.001
Epoch  39 | train: 0.0941 | val: 0.1432 | acc: 96.38% | AUC: 0.984  | LR: 0.001
Epoch  40 | train: 0.0904 | val: 0.1396 | acc: 95.45% | AUC: 0.985  | LR: 0.001
Epoch  41 | train: 0.0895 | val: 0.1788 | acc: 96.80% | AUC: 0.982  | LR: 0.001
Epoch  42 | train: 0.0929 | val: 0.1520 | acc: 93.87% | AUC: 0.983  | LR: 0.001
Epoch  43 | train: 0.0911 | val: 0.1671 | acc: 96.98% | AUC: 0.983  | LR: 0.0005
Epoch  44 | train: 0.0726 | val: 0.1357 | acc: 95.59% | AUC: 0.985  | LR: 0.0005
Epoch  45 | train: 0.0669 | val: 0.1393 | acc: 96.19% | AUC: 0.985  | LR: 0.0005
Epoch  46 | train: 0.0679 | val: 0.1422 | acc: 96.61% | AUC: 0.985  | LR: 0.0005
Epoch  47 | train: 0.0661 | val: 0.1402 | acc: 96.24% | AUC: 0.985  | LR: 0.0005
Epoch  48 | train: 0.0671 | val: 0.1425 | acc: 96.84% | AUC: 0.985  | LR: 0.0005
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold2.pth
Epoch  49 | train: 0.0605 | val: 0.1328 | acc: 96.38% | AUC: 0.986  | LR: 0.0005
Epoch  50 | train: 0.0608 | val: 0.1466 | acc: 96.70% | AUC: 0.985  | LR: 0.0005
Epoch  51 | train: 0.0599 | val: 0.1659 | acc: 97.08% | AUC: 0.985  | LR: 0.0005
Epoch  52 | train: 0.0637 | val: 0.1466 | acc: 96.10% | AUC: 0.984  | LR: 0.0005
Epoch  53 | train: 0.0595 | val: 0.1512 | acc: 97.08% | AUC: 0.985  | LR: 0.0005
Epoch  54 | train: 0.0592 | val: 0.1680 | acc: 97.12% | AUC: 0.985  | LR: 0.0005
Epoch  55 | train: 0.0608 | val: 0.1752 | acc: 97.31% | AUC: 0.985  | LR: 0.0005
Epoch  56 | train: 0.0562 | val: 0.1458 | acc: 96.94% | AUC: 0.986  | LR: 0.0005
Epoch  57 | train: 0.0535 | val: 0.1909 | acc: 96.84% | AUC: 0.983  | LR: 0.0005
Epoch  58 | train: 0.0546 | val: 0.1528 | acc: 96.19% | AUC: 0.984  | LR: 0.0005
Epoch  59 | train: 0.0561 | val: 0.1948 | acc: 97.59% | AUC: 0.984  | LR: 0.0005
Epoch  60 | train: 0.0591 | val: 0.1651 | acc: 96.52% | AUC: 0.983  | LR: 0.0005
Epoch  61 | train: 0.0509 | val: 0.1563 | acc: 96.10% | AUC: 0.985  | LR: 0.0005
Epoch  62 | train: 0.0544 | val: 0.1519 | acc: 95.50% | AUC: 0.985  | LR: 0.0005
Epoch  63 | train: 0.0556 | val: 0.1798 | acc: 96.89% | AUC: 0.985  | LR: 0.0005
Epoch  64 | train: 0.0551 | val: 0.2068 | acc: 97.40% | AUC: 0.983  | LR: 0.0005
Early stopping efter 65 epoker.
Klar!

Utvärderar bästa modellen för Fold 2...
-> Slutresultat Fold 2: Train Loss: 0.0564 | Val Loss: 0.1328 | AUC: 0.9861

========================================
 FOLD 3/10
========================================
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch   0 | train: 4.1023 | val: 0.4621 | acc: 92.06% | AUC: 0.862  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch   1 | train: 0.4304 | val: 0.3363 | acc: 87.93% | AUC: 0.933  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch   2 | train: 0.4073 | val: 0.3196 | acc: 95.26% | AUC: 0.939  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch   3 | train: 0.3138 | val: 0.2245 | acc: 96.15% | AUC: 0.952  | LR: 0.001
Epoch   4 | train: 0.2757 | val: 0.3280 | acc: 93.27% | AUC: 0.944  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch   5 | train: 0.3139 | val: 0.1940 | acc: 96.33% | AUC: 0.971  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch   6 | train: 0.2442 | val: 0.1692 | acc: 96.98% | AUC: 0.980  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch   7 | train: 0.1818 | val: 0.1818 | acc: 93.78% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch   8 | train: 0.1707 | val: 0.1312 | acc: 96.98% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch   9 | train: 0.1559 | val: 0.1259 | acc: 96.33% | AUC: 0.987  | LR: 0.001
Epoch  10 | train: 0.1608 | val: 0.1525 | acc: 95.03% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch  11 | train: 0.1532 | val: 0.1340 | acc: 97.26% | AUC: 0.989  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch  12 | train: 0.1422 | val: 0.1145 | acc: 97.86% | AUC: 0.989  | LR: 0.001
Epoch  13 | train: 0.1514 | val: 0.1436 | acc: 97.86% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch  14 | train: 0.1433 | val: 0.1081 | acc: 96.66% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_no_local_pooling_fold3.pth
Epoch  15 | train: 0.1264 | val: 0.0993 | acc: 98.05% | AUC: 0.992  | LR: 0.001
Epoch  16 | train: 0.1229 | val: 0.1104 | acc: 97.17% | AUC: 0.989  | LR: 0.001
Epoch  17 | train: 0.1217 | val: 0.1161 | acc: 96.98% | AUC: 0.988  | LR: 0.001
Epoch  18 | train: 0.1107 | val: 0.1089 | acc: 97.96% | AUC: 0.991  | LR: 0.001
Epoch  19 | train: 0.1054 | val: 0.1392 | acc: 98.24% | AUC: 0.989  | LR: 0.001

,fold,train_loss,val_loss,val_accuracy,val_auc,val_spec,val_sens,tn,fp,fn,tp
0,1,0.121852,0.199031,94.707521,0.977092,0.954377,0.895911,1799,86,28,241
1,2,0.056426,0.132752,96.378830,0.986126,0.966048,0.947955,1821,64,14,255
2,3,0.095675,0.099349,98.050139,0.991952,0.985676,0.944238,1858,27,15,254
3,4,0.100718,0.131739,97.165428,0.988297,0.979288,0.918216,1844,39,22,247
4,5,0.118998,0.167731,96.005574,0.984031,0.968153,0.903346,1824,60,26,243
5,6,0.123459,0.420459,97.446611,0.980511,0.982493,0.918216,1852,33,22,247
6,7,0.057557,0.323113,95.680446,0.981101,0.964968,0.899628,1818,66,27,242
7,8,0.210302,0.386982,90.343547,0.924864,0.918302,0.799257,1731,154,54,215
8,9,0.092703,0.146815,97.538319,0.988824,0.984599,0.911111,1854,29,24,246
9,10,0.114665,0.152552,98.327138,0.994532,0.995218,0.900000,1873,9,27,243

In [1]:
import duckdb
from networks.cnn_batchnorm1d import CNNModel
from networks.cnn_network import build_dataloaders


con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


train_rows = df[df['set'] == 'train']
val_rows   = df[df['set'] == 'val']
test_rows  = df[df['set'] == 'test']

drop_indices = train_rows[train_rows['label'] == 0].sample(frac=0.7).index

train_rows = train_rows.drop(drop_indices)
train_rows = train_rows[train_rows['label'].isin([0,1])]
val_rows = val_rows[val_rows['label'].isin([0,1])]

print(f"Antal utan m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 0])}")
print(f"Antal med m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 1])}")

CNN = CNNModel()
cnn_train_dl, cnn_val_dl, _ = build_dataloaders(train_rows, val_rows, val_rows)
CNN.reset_weights()
CNN.retrain(cnn_train_dl,cnn_val_dl,patience=15)

con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


k_fold_rows = df[df['set'].isin(['train','val']) ].copy()
k_fold_rows = k_fold_rows[k_fold_rows['label'].isin([0,1])]
drop_indices = k_fold_rows[k_fold_rows['label'] == 0].sample(frac=0.7).index
k_fold_rows = k_fold_rows.drop(drop_indices)
print(f"Totalt antal utan m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 0])}")
print(f"Totalt antal med m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 1])}")

test_rows  = df[df['set'] == 'test']


CNN = CNNModel()
CNN.retrain_with_k_fold(k_fold_rows)

Antal utan m-komponent i träningsdatan: 17903
Antal med m-komponent i träningsdatan: 2553
Total parameters: 633,122
  -> ny bästa modell sparad till ../models/cnn_batchnorm.pth
Epoch   0 | train: 0.6081 | val: 0.4717 | acc: 91.72% | AUC: 0.921  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm.pth
Epoch   1 | train: 0.3968 | val: 0.2797 | acc: 96.23% | AUC: 0.960  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm.pth
Epoch   2 | train: 0.2897 | val: 0.1479 | acc: 98.33% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm.pth
Epoch   3 | train: 0.1982 | val: 0.0980 | acc: 98.75% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm.pth
Epoch   4 | train: 0.1938 | val: 0.1199 | acc: 97.72% | AUC: 0.995  | LR: 0.001
Epoch   5 | train: 0.1563 | val: 0.0827 | acc: 98.63% | AUC: 0.995  | LR: 0.001
Epoch   6 | train: 0.1522 | val: 0.0866 | acc: 98.51% | AUC: 0.995  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm.pth
Epoch   7 | train: 0.1402 | val: 0.1075 | acc: 97.60% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm.pth
Epoch   8 | train: 0.1300 | val: 0.0737 | acc: 98.48% | AUC: 0.996  | LR: 0.001
Epoch   9 | train: 0.1247 | val: 0.1021 | acc: 97.57% | AUC: 0.996  | LR: 0.001
Epoch  10 | train: 0.1191 | val: 0.0695 | acc: 98.87% | AUC: 0.995  | LR: 0.001
Epoch  11 | train: 0.1150 | val: 0.1138 | acc: 96.99% | AUC: 0.995  | LR: 0.001
Epoch  12 | train: 0.1145 | val: 0.0614 | acc: 98.87% | AUC: 0.995  | LR: 0.001
Epoch  13 | train: 0.1075 | val: 0.0762 | acc: 98.14% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm.pth
Epoch  14 | train: 0.0994 | val: 0.0915 | acc: 97.81% | AUC: 0.997  | LR: 0.001
Epoch  15 | train: 0.0985 | val: 0.0760 | acc: 98.54% | AUC: 0.995  | LR: 0.001
Epoch  16 | train: 0.0950 | val: 0.1206 | acc: 96.44% | AUC: 0.995  | LR: 0.001
Epoch  17 | train: 0.0917 | val: 0.0903 | acc: 97.66% | AUC: 0.996  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm.pth
Epoch  18 | train: 0.0967 | val: 0.0846 | acc: 97.78% | AUC: 0.997  | LR: 0.001
Epoch  19 | train: 0.0877 | val: 0.0992 | acc: 97.02% | AUC: 0.996  | LR: 0.001
Epoch  20 | train: 0.0802 | val: 0.0611 | acc: 98.60% | AUC: 0.996  | LR: 0.001
Epoch  21 | train: 0.0762 | val: 0.0568 | acc: 98.90% | AUC: 0.996  | LR: 0.001
Epoch  22 | train: 0.0736 | val: 0.0620 | acc: 98.36% | AUC: 0.996  | LR: 0.001
Epoch  23 | train: 0.0750 | val: 0.0794 | acc: 98.21% | AUC: 0.997  | LR: 0.001
Epoch  24 | train: 0.0726 | val: 0.1036 | acc: 96.74% | AUC: 0.995  | LR: 0.001
Epoch  25 | train: 0.0740 | val: 0.0647 | acc: 98.39% | AUC: 0.995  | LR: 0.001
Epoch  26 | train: 0.0705 | val: 0.0603 | acc: 98.57% | AUC: 0.995  | LR: 0.001
Epoch  27 | train: 0.0677 | val: 0.1003 | acc: 96.78% | AUC: 0.995  | LR: 0.001
Epoch  28 | train: 0.0636 | val: 0.0769 | acc: 97.93% | AUC: 0.995  | LR: 0.001
Epoch  29 | train: 0.0663 | val: 0.0674 | acc: 98.27% | AUC: 0.996  | LR: 0.001
Epoch  30 | train: 0.0587 | val: 0.1068 | acc: 96.32% | AUC: 0.996  | LR: 0.001
Epoch  31 | train: 0.0620 | val: 0.0827 | acc: 97.57% | AUC: 0.996  | LR: 0.001
Epoch  32 | train: 0.0575 | val: 0.0506 | acc: 98.90% | AUC: 0.996  | LR: 0.001
Epoch  33 | train: 0.0577 | val: 0.0830 | acc: 97.41% | AUC: 0.996  | LR: 0.001
Epoch  34 | train: 0.0610 | val: 0.0574 | acc: 98.75% | AUC: 0.996  | LR: 0.001
Epoch  35 | train: 0.0517 | val: 0.0780 | acc: 97.69% | AUC: 0.996  | LR: 0.001
Epoch  36 | train: 0.0454 | val: 0.0728 | acc: 98.21% | AUC: 0.995  | LR: 0.001
Epoch  37 | train: 0.0493 | val: 0.0635 | acc: 98.84% | AUC: 0.995  | LR: 0.001
Epoch  38 | train: 0.0466 | val: 0.0836 | acc: 97.57% | AUC: 0.995  | LR: 0.001
Epoch  39 | train: 0.0410 | val: 0.0643 | acc: 98.57% | AUC: 0.995  | LR: 0.001
Epoch  40 | train: 0.0425 | val: 0.0730 | acc: 98.14% | AUC: 0.995  | LR: 0.001
Epoch  41 | train: 0.0422 | val: 0.0792 | acc: 97.63% | AUC: 0.996  | LR: 0.001
Epoch  42 | train: 0.0404 | val: 0.0550 | acc: 99.06% | AUC: 0.995  | LR: 0.001
Epoch  43 | train: 0.0390 | val: 0.0650 | acc: 98.78% | AUC: 0.995  | LR: 0.001
Epoch  44 | train: 0.0347 | val: 0.0884 | acc: 97.51% | AUC: 0.996  | LR: 0.001
Epoch  45 | train: 0.0359 | val: 0.0674 | acc: 98.57% | AUC: 0.995  | LR: 0.001
Epoch  46 | train: 0.0338 | val: 0.0675 | acc: 98.63% | AUC: 0.995  | LR: 0.001
Epoch  47 | train: 0.0378 | val: 0.0655 | acc: 98.57% | AUC: 0.995  | LR: 0.001
Early stopping efter 48 epoker.
Klar!
Totalt antal utan m-komponent i K-fold poolen: 18848
Totalt antal med m-komponent i K-fold poolen: 2692
Total parameters: 633,122
--- Startar 10-Fold Cross Validation ---

========================================
 FOLD 1/10
========================================
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold1.pth
Epoch   0 | train: 0.4985 | val: 0.4239 | acc: 93.82% | AUC: 0.898  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold1.pth
Epoch   1 | train: 0.3576 | val: 0.3646 | acc: 94.84% | AUC: 0.947  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold1.pth
Epoch   2 | train: 0.2405 | val: 0.3587 | acc: 77.98% | AUC: 0.967  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold1.pth
Epoch   3 | train: 0.1865 | val: 0.1859 | acc: 95.68% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold1.pth
Epoch   4 | train: 0.1422 | val: 0.1730 | acc: 97.40% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold1.pth
Epoch   5 | train: 0.1328 | val: 0.1599 | acc: 96.05% | AUC: 0.988  | LR: 0.001
Epoch   6 | train: 0.1314 | val: 0.1715 | acc: 94.24% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold1.pth
Epoch   7 | train: 0.1145 | val: 0.1516 | acc: 97.63% | AUC: 0.991  | LR: 0.001
Epoch   8 | train: 0.1171 | val: 0.1538 | acc: 96.05% | AUC: 0.989  | LR: 0.001
Epoch   9 | train: 0.1023 | val: 0.1437 | acc: 96.24% | AUC: 0.990  | LR: 0.001
Epoch  10 | train: 0.1014 | val: 0.1476 | acc: 96.93% | AUC: 0.989  | LR: 0.001
Epoch  11 | train: 0.0930 | val: 0.1431 | acc: 96.38% | AUC: 0.990  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold1.pth
Epoch  12 | train: 0.0881 | val: 0.1869 | acc: 97.91% | AUC: 0.991  | LR: 0.001
Epoch  13 | train: 0.0841 | val: 0.1549 | acc: 97.26% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold1.pth
Epoch  14 | train: 0.0920 | val: 0.1362 | acc: 96.42% | AUC: 0.992  | LR: 0.001
Epoch  15 | train: 0.0799 | val: 0.1419 | acc: 97.54% | AUC: 0.991  | LR: 0.001
Epoch  16 | train: 0.0777 | val: 0.1407 | acc: 96.28% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold1.pth
Epoch  17 | train: 0.0805 | val: 0.1357 | acc: 97.35% | AUC: 0.992  | LR: 0.001
Epoch  18 | train: 0.0735 | val: 0.1601 | acc: 96.84% | AUC: 0.989  | LR: 0.001
Epoch  19 | train: 0.0687 | val: 0.1625 | acc: 95.77% | AUC: 0.991  | LR: 0.001
Epoch  20 | train: 0.0663 | val: 0.1520 | acc: 97.21% | AUC: 0.991  | LR: 0.001
Epoch  21 | train: 0.0630 | val: 0.1693 | acc: 97.72% | AUC: 0.990  | LR: 0.001
Epoch  22 | train: 0.0610 | val: 0.2148 | acc: 97.68% | AUC: 0.990  | LR: 0.001
Epoch  23 | train: 0.0505 | val: 0.1787 | acc: 96.93% | AUC: 0.991  | LR: 0.001
Epoch  24 | train: 0.0505 | val: 0.1825 | acc: 97.40% | AUC: 0.991  | LR: 0.001
Epoch  25 | train: 0.0469 | val: 0.1903 | acc: 97.35% | AUC: 0.990  | LR: 0.001
Epoch  26 | train: 0.0453 | val: 0.1922 | acc: 96.84% | AUC: 0.990  | LR: 0.001
Epoch  27 | train: 0.0471 | val: 0.1867 | acc: 96.47% | AUC: 0.990  | LR: 0.001
Epoch  28 | train: 0.0466 | val: 0.2615 | acc: 97.82% | AUC: 0.990  | LR: 0.001
Epoch  29 | train: 0.0386 | val: 0.1997 | acc: 97.31% | AUC: 0.988  | LR: 0.001
Epoch  30 | train: 0.0402 | val: 0.2118 | acc: 97.68% | AUC: 0.990  | LR: 0.001
Epoch  31 | train: 0.0368 | val: 0.2479 | acc: 97.58% | AUC: 0.989  | LR: 0.001
Epoch  32 | train: 0.0424 | val: 0.2767 | acc: 97.86% | AUC: 0.990  | LR: 0.001
Early stopping efter 33 epoker.
Klar!

Utvärderar bästa modellen för Fold 1...
-> Slutresultat Fold 1: Train Loss: 0.0578 | Val Loss: 0.1357 | AUC: 0.9921

========================================
 FOLD 2/10
========================================
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch   0 | train: 0.5386 | val: 0.4275 | acc: 93.54% | AUC: 0.905  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch   1 | train: 0.3176 | val: 0.2395 | acc: 96.10% | AUC: 0.969  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch   2 | train: 0.2276 | val: 0.2845 | acc: 83.56% | AUC: 0.980  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch   3 | train: 0.2038 | val: 0.1406 | acc: 96.47% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch   4 | train: 0.1557 | val: 0.1225 | acc: 96.70% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch   5 | train: 0.1324 | val: 0.1228 | acc: 96.33% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch   6 | train: 0.1263 | val: 0.1086 | acc: 96.38% | AUC: 0.991  | LR: 0.001
Epoch   7 | train: 0.1243 | val: 0.1078 | acc: 96.66% | AUC: 0.990  | LR: 0.001
Epoch   8 | train: 0.1151 | val: 0.1076 | acc: 97.17% | AUC: 0.991  | LR: 0.001
Epoch   9 | train: 0.1118 | val: 0.1150 | acc: 95.49% | AUC: 0.990  | LR: 0.001
Epoch  10 | train: 0.1032 | val: 0.1157 | acc: 97.26% | AUC: 0.985  | LR: 0.001
Epoch  11 | train: 0.0965 | val: 0.1119 | acc: 96.61% | AUC: 0.987  | LR: 0.001
Epoch  12 | train: 0.0881 | val: 0.1265 | acc: 97.58% | AUC: 0.989  | LR: 0.001
Epoch  13 | train: 0.0881 | val: 0.1185 | acc: 94.75% | AUC: 0.991  | LR: 0.001
Epoch  14 | train: 0.0882 | val: 0.1178 | acc: 97.17% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch  15 | train: 0.0825 | val: 0.1288 | acc: 93.08% | AUC: 0.991  | LR: 0.001
Epoch  16 | train: 0.0899 | val: 0.1065 | acc: 96.56% | AUC: 0.988  | LR: 0.001
Epoch  17 | train: 0.0737 | val: 0.1086 | acc: 97.21% | AUC: 0.989  | LR: 0.001
Epoch  18 | train: 0.0740 | val: 0.1083 | acc: 96.89% | AUC: 0.990  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch  19 | train: 0.0678 | val: 0.1048 | acc: 97.07% | AUC: 0.992  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch  20 | train: 0.0839 | val: 0.1057 | acc: 96.89% | AUC: 0.992  | LR: 0.001
Epoch  21 | train: 0.0680 | val: 0.1130 | acc: 96.70% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold2.pth
Epoch  22 | train: 0.0619 | val: 0.1032 | acc: 96.47% | AUC: 0.993  | LR: 0.001
Epoch  23 | train: 0.0612 | val: 0.1165 | acc: 96.28% | AUC: 0.989  | LR: 0.001
Epoch  24 | train: 0.0530 | val: 0.1183 | acc: 96.38% | AUC: 0.989  | LR: 0.001
Epoch  25 | train: 0.0548 | val: 0.1251 | acc: 97.35% | AUC: 0.990  | LR: 0.001
Epoch  26 | train: 0.0508 | val: 0.1350 | acc: 97.31% | AUC: 0.990  | LR: 0.001
Epoch  27 | train: 0.0492 | val: 0.1403 | acc: 97.35% | AUC: 0.986  | LR: 0.001
Epoch  28 | train: 0.0433 | val: 0.1329 | acc: 97.40% | AUC: 0.989  | LR: 0.001
Epoch  29 | train: 0.0498 | val: 0.1339 | acc: 97.45% | AUC: 0.991  | LR: 0.001
Epoch  30 | train: 0.0513 | val: 0.1265 | acc: 97.12% | AUC: 0.988  | LR: 0.001
Epoch  31 | train: 0.0430 | val: 0.1405 | acc: 97.31% | AUC: 0.987  | LR: 0.001
Epoch  32 | train: 0.0379 | val: 0.1547 | acc: 97.31% | AUC: 0.985  | LR: 0.001
Epoch  33 | train: 0.0389 | val: 0.1319 | acc: 96.89% | AUC: 0.989  | LR: 0.001
Epoch  34 | train: 0.0347 | val: 0.1219 | acc: 96.89% | AUC: 0.991  | LR: 0.001
Epoch  35 | train: 0.0364 | val: 0.1692 | acc: 97.63% | AUC: 0.988  | LR: 0.001
Epoch  36 | train: 0.0366 | val: 0.1683 | acc: 97.72% | AUC: 0.987  | LR: 0.001
Epoch  37 | train: 0.0336 | val: 0.1786 | acc: 97.58% | AUC: 0.986  | LR: 0.001
Early stopping efter 38 epoker.
Klar!

Utvärderar bästa modellen för Fold 2...
-> Slutresultat Fold 2: Train Loss: 0.0534 | Val Loss: 0.1032 | AUC: 0.9926

========================================
 FOLD 3/10
========================================
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold3.pth
Epoch   0 | train: 0.5268 | val: 0.4618 | acc: 93.55% | AUC: 0.899  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold3.pth
Epoch   1 | train: 0.2886 | val: 0.2872 | acc: 89.18% | AUC: 0.962  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold3.pth
Epoch   2 | train: 0.1955 | val: 0.2213 | acc: 96.80% | AUC: 0.975  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold3.pth
Epoch   3 | train: 0.1663 | val: 0.1694 | acc: 96.01% | AUC: 0.982  | LR: 0.001
Epoch   4 | train: 0.1350 | val: 0.1743 | acc: 96.15% | AUC: 0.981  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold3.pth
Epoch   5 | train: 0.1238 | val: 0.1583 | acc: 95.13% | AUC: 0.986  | LR: 0.001
Epoch   6 | train: 0.1102 | val: 0.1819 | acc: 96.80% | AUC: 0.983  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold3.pth
Epoch   7 | train: 0.1063 | val: 0.1555 | acc: 96.33% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold3.pth
Epoch   8 | train: 0.1026 | val: 0.1489 | acc: 94.75% | AUC: 0.987  | LR: 0.001
Epoch   9 | train: 0.0978 | val: 0.1477 | acc: 97.03% | AUC: 0.987  | LR: 0.001
Epoch  10 | train: 0.0948 | val: 0.1421 | acc: 96.56% | AUC: 0.987  | LR: 0.001
Epoch  11 | train: 0.0958 | val: 0.1535 | acc: 95.36% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold3.pth
Epoch  12 | train: 0.0910 | val: 0.1640 | acc: 96.84% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold3.pth
Epoch  13 | train: 0.0800 | val: 0.1394 | acc: 96.84% | AUC: 0.990  | LR: 0.001
Epoch  14 | train: 0.0774 | val: 0.1823 | acc: 96.61% | AUC: 0.987  | LR: 0.001
Epoch  15 | train: 0.0746 | val: 0.1485 | acc: 95.50% | AUC: 0.988  | LR: 0.001
Epoch  16 | train: 0.0759 | val: 0.1798 | acc: 97.08% | AUC: 0.985  | LR: 0.001
Epoch  17 | train: 0.0646 | val: 0.1558 | acc: 96.75% | AUC: 0.988  | LR: 0.001
Epoch  18 | train: 0.0669 | val: 0.2038 | acc: 97.03% | AUC: 0.986  | LR: 0.001
Epoch  19 | train: 0.0651 | val: 0.1861 | acc: 97.03% | AUC: 0.985  | LR: 0.001
Epoch  20 | train: 0.0599 | val: 0.1758 | acc: 96.52% | AUC: 0.987  | LR: 0.001
Epoch  21 | train: 0.0603 | val: 0.2202 | acc: 97.45% | AUC: 0.983  | LR: 0.001
Epoch  22 | train: 0.0540 | val: 0.1921 | acc: 96.70% | AUC: 0.986  | LR: 0.001
Epoch  23 | train: 0.0539 | val: 0.1539 | acc: 96.47% | AUC: 0.987  | LR: 0.001
Epoch  24 | train: 0.0521 | val: 0.2781 | acc: 97.73% | AUC: 0.984  | LR: 0.001
Epoch  25 | train: 0.0602 | val: 0.1853 | acc: 96.84% | AUC: 0.986  | LR: 0.001
Epoch  26 | train: 0.0454 | val: 0.2102 | acc: 97.21% | AUC: 0.987  | LR: 0.001
Epoch  27 | train: 0.0463 | val: 0.1887 | acc: 96.56% | AUC: 0.985  | LR: 0.001
Epoch  28 | train: 0.0402 | val: 0.2057 | acc: 97.35% | AUC: 0.987  | LR: 0.001
Early stopping efter 29 epoker.
Klar!

Utvärderar bästa modellen för Fold 3...
-> Slutresultat Fold 3: Train Loss: 0.0655 | Val Loss: 0.1394 | AUC: 0.9896

========================================
 FOLD 4/10
========================================
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold4.pth
Epoch   0 | train: 0.6216 | val: 0.5039 | acc: 91.45% | AUC: 0.862  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold4.pth
Epoch   1 | train: 0.3860 | val: 0.3752 | acc: 94.33% | AUC: 0.933  | LR: 0.001
Epoch   2 | train: 0.3154 | val: 0.3646 | acc: 91.83% | AUC: 0.932  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold4.pth
Epoch   3 | train: 0.2444 | val: 0.2267 | acc: 95.26% | AUC: 0.971  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold4.pth
Epoch   4 | train: 0.1831 | val: 0.1754 | acc: 96.24% | AUC: 0.982  | LR: 0.001
Epoch   5 | train: 0.1525 | val: 0.1760 | acc: 96.70% | AUC: 0.978  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold4.pth
Epoch   6 | train: 0.1382 | val: 0.1463 | acc: 97.12% | AUC: 0.987  | LR: 0.001
Epoch   7 | train: 0.1295 | val: 0.1548 | acc: 97.68% | AUC: 0.986  | LR: 0.001
Epoch   8 | train: 0.1340 | val: 0.1670 | acc: 98.00% | AUC: 0.985  | LR: 0.001
Epoch   9 | train: 0.1239 | val: 0.1497 | acc: 95.87% | AUC: 0.985  | LR: 0.001
Epoch  10 | train: 0.1087 | val: 0.1693 | acc: 98.00% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold4.pth
Epoch  11 | train: 0.0947 | val: 0.1436 | acc: 97.07% | AUC: 0.987  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold4.pth
Epoch  12 | train: 0.1004 | val: 0.1458 | acc: 97.12% | AUC: 0.988  | LR: 0.001
Epoch  13 | train: 0.0929 | val: 0.1520 | acc: 97.82% | AUC: 0.987  | LR: 0.001
Epoch  14 | train: 0.0867 | val: 0.1666 | acc: 97.49% | AUC: 0.984  | LR: 0.001
Epoch  15 | train: 0.0816 | val: 0.1569 | acc: 97.31% | AUC: 0.987  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold4.pth
Epoch  16 | train: 0.0935 | val: 0.1617 | acc: 97.96% | AUC: 0.988  | LR: 0.001
Epoch  17 | train: 0.0827 | val: 0.1550 | acc: 97.35% | AUC: 0.984  | LR: 0.001
Epoch  18 | train: 0.0714 | val: 0.1663 | acc: 96.89% | AUC: 0.983  | LR: 0.001
Epoch  19 | train: 0.0715 | val: 0.1664 | acc: 97.35% | AUC: 0.985  | LR: 0.001
Epoch  20 | train: 0.0662 | val: 0.1704 | acc: 97.40% | AUC: 0.982  | LR: 0.001
Epoch  21 | train: 0.0644 | val: 0.1735 | acc: 96.33% | AUC: 0.983  | LR: 0.001
Epoch  22 | train: 0.0663 | val: 0.1868 | acc: 97.21% | AUC: 0.982  | LR: 0.001
Epoch  23 | train: 0.0631 | val: 0.1941 | acc: 97.07% | AUC: 0.983  | LR: 0.001
Epoch  24 | train: 0.0607 | val: 0.1897 | acc: 98.14% | AUC: 0.985  | LR: 0.001
Epoch  25 | train: 0.0753 | val: 0.2283 | acc: 90.85% | AUC: 0.978  | LR: 0.001
Epoch  26 | train: 0.0752 | val: 0.1706 | acc: 96.89% | AUC: 0.985  | LR: 0.001
Early stopping efter 27 epoker.
Klar!

Utvärderar bästa modellen för Fold 4...
-> Slutresultat Fold 4: Train Loss: 0.0742 | Val Loss: 0.1617 | AUC: 0.9879

========================================
 FOLD 5/10
========================================
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold5.pth
Epoch   0 | train: 0.5209 | val: 0.4480 | acc: 93.49% | AUC: 0.911  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold5.pth
Epoch   1 | train: 0.2850 | val: 0.2466 | acc: 96.24% | AUC: 0.973  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold5.pth
Epoch   2 | train: 0.2254 | val: 0.1990 | acc: 96.84% | AUC: 0.979  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold5.pth
Epoch   3 | train: 0.1717 | val: 0.1682 | acc: 94.56% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold5.pth
Epoch   4 | train: 0.1546 | val: 0.1344 | acc: 96.56% | AUC: 0.991  | LR: 0.001
Epoch   5 | train: 0.1349 | val: 0.1313 | acc: 97.72% | AUC: 0.990  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold5.pth
Epoch   6 | train: 0.1198 | val: 0.1199 | acc: 97.68% | AUC: 0.992  | LR: 0.001
Epoch   7 | train: 0.1087 | val: 0.1231 | acc: 97.72% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold5.pth
Epoch   8 | train: 0.1191 | val: 0.1129 | acc: 97.03% | AUC: 0.992  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold5.pth
Epoch   9 | train: 0.1022 | val: 0.1283 | acc: 97.77% | AUC: 0.992  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_fold5.pth
Epoch  10 | train: 0.0989 | val: 0.1071 | acc: 97.72% | AUC: 0.994  | LR: 0.001

,fold,train_loss,val_loss,val_accuracy,val_auc,val_spec,val_sens,tn,fp,fn,tp
0,1,0.057810,0.135714,97.352531,0.992144,0.978757,0.937037,1843,40,17,253
1,2,0.053361,0.103239,96.470042,0.992551,0.968136,0.940741,1823,60,16,254
2,3,0.065466,0.139423,96.843083,0.989629,0.975597,0.918216,1839,46,22,247
3,4,0.074243,0.161690,97.956340,0.987948,0.987261,0.925651,1860,24,20,249
4,5,0.051941,0.098871,97.165428,0.994727,0.973978,0.955390,1834,49,12,257
5,6,0.050924,0.105572,97.724106,0.992978,0.983546,0.933086,1853,31,18,251
6,7,0.052010,0.092802,97.584765,0.994189,0.979299,0.951673,1845,39,13,256
7,8,0.090618,0.155616,96.003717,0.987926,0.964418,0.929368,1816,67,19,250
8,9,0.129748,0.198991,97.213191,0.982460,0.983546,0.892193,1853,31,29,240
9,10,0.097127,0.146258,97.539461,0.990575,0.988859,0.881041,1864,21,32,237

In [1]:
import duckdb
from networks.cnn_batchnorm_and_local_pool import CNNModel
from networks.cnn_network import build_dataloaders


con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


train_rows = df[df['set'] == 'train']
val_rows   = df[df['set'] == 'val']
test_rows  = df[df['set'] == 'test']

drop_indices = train_rows[train_rows['label'] == 0].sample(frac=0.7).index

train_rows = train_rows.drop(drop_indices)
train_rows = train_rows[train_rows['label'].isin([0,1])]
val_rows = val_rows[val_rows['label'].isin([0,1])]

print(f"Antal utan m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 0])}")
print(f"Antal med m-komponent i träningsdatan: {len(train_rows[train_rows['label'] == 1])}")

CNN = CNNModel()
cnn_train_dl, cnn_val_dl, _ = build_dataloaders(train_rows, val_rows, val_rows)
CNN.reset_weights()
CNN.retrain(cnn_train_dl,cnn_val_dl,patience=15)

con = duckdb.connect('../capillary.db')
df = con.execute(""" 
                 SELECT row_id, value,fractions, boundaries,albumin,antitrypsin,orosomukoid,haptoglobin,crp,igg,iga,igm, label, set, interpretation
                 FROM protein_data
                 WHERE value IS NOT NULL
                 AND observation_nr = 1
                 AND analysis IS NOT NULL
                 AND protein_value IS NOT NULL
                 """).df()
con.close()


k_fold_rows = df[df['set'].isin(['train','val']) ].copy()
k_fold_rows = k_fold_rows[k_fold_rows['label'].isin([0,1])]
drop_indices = k_fold_rows[k_fold_rows['label'] == 0].sample(frac=0.7).index
k_fold_rows = k_fold_rows.drop(drop_indices)
print(f"Totalt antal utan m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 0])}")
print(f"Totalt antal med m-komponent i K-fold poolen: {len(k_fold_rows[k_fold_rows['label'] == 1])}")

test_rows  = df[df['set'] == 'test']


CNN = CNNModel()
CNN.retrain_with_k_fold(k_fold_rows)

Antal utan m-komponent i träningsdatan: 17903
Antal med m-komponent i träningsdatan: 2553
Total parameters: 172,322
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool.pth
Epoch   0 | train: 0.5048 | val: 0.2750 | acc: 97.38% | AUC: 0.935  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool.pth
Epoch   1 | train: 0.3000 | val: 0.1658 | acc: 97.72% | AUC: 0.970  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool.pth
Epoch   2 | train: 0.2290 | val: 0.1125 | acc: 98.45% | AUC: 0.992  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool.pth
Epoch   3 | train: 0.2085 | val: 0.1257 | acc: 97.05% | AUC: 0.994  | LR: 0.001
Epoch   4 | train: 0.1782 | val: 0.1027 | acc: 98.42% | AUC: 0.993  | LR: 0.001
Epoch   5 | train: 0.1639 | val: 0.4116 | acc: 79.40% | AUC: 0.987  | LR: 0.001
Epoch   6 | train: 0.1451 | val: 0.1353 | acc: 95.65% | AUC: 0.993  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool.pth
Epoch   7 | train: 0.1381 | val: 0.1446 | acc: 96.14% | AUC: 0.995  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool.pth
Epoch   8 | train: 0.1300 | val: 0.0795 | acc: 97.90% | AUC: 0.997  | LR: 0.001
Epoch   9 | train: 0.1216 | val: 0.1371 | acc: 95.92% | AUC: 0.995  | LR: 0.001
Epoch  10 | train: 0.1153 | val: 0.1855 | acc: 93.22% | AUC: 0.992  | LR: 0.001
Epoch  11 | train: 0.1096 | val: 0.0993 | acc: 97.32% | AUC: 0.995  | LR: 0.001
Epoch  12 | train: 0.1074 | val: 0.0680 | acc: 98.48% | AUC: 0.994  | LR: 0.001
Epoch  13 | train: 0.0977 | val: 0.1161 | acc: 96.78% | AUC: 0.996  | LR: 0.001
Epoch  14 | train: 0.0940 | val: 0.0767 | acc: 98.14% | AUC: 0.995  | LR: 0.001
Epoch  15 | train: 0.1014 | val: 0.2147 | acc: 90.96% | AUC: 0.995  | LR: 0.001
Epoch  16 | train: 0.0980 | val: 0.0752 | acc: 97.96% | AUC: 0.995  | LR: 0.001
Epoch  17 | train: 0.0804 | val: 0.0844 | acc: 97.54% | AUC: 0.995  | LR: 0.001
Epoch  18 | train: 0.0836 | val: 0.0684 | acc: 97.96% | AUC: 0.994  | LR: 0.001
Epoch  19 | train: 0.0728 | val: 0.0956 | acc: 96.90% | AUC: 0.995  | LR: 0.001
Epoch  20 | train: 0.0734 | val: 0.0814 | acc: 97.44% | AUC: 0.994  | LR: 0.001
Epoch  21 | train: 0.0752 | val: 0.0577 | acc: 98.48% | AUC: 0.994  | LR: 0.001
Epoch  22 | train: 0.0741 | val: 0.0781 | acc: 97.69% | AUC: 0.995  | LR: 0.001
Epoch  23 | train: 0.0641 | val: 0.0563 | acc: 98.30% | AUC: 0.996  | LR: 0.001
Epoch  24 | train: 0.0657 | val: 0.0633 | acc: 98.30% | AUC: 0.994  | LR: 0.001
Epoch  25 | train: 0.0632 | val: 0.0488 | acc: 98.78% | AUC: 0.994  | LR: 0.001
Epoch  26 | train: 0.0580 | val: 0.0642 | acc: 97.96% | AUC: 0.994  | LR: 0.001
Epoch  27 | train: 0.0619 | val: 0.0809 | acc: 97.26% | AUC: 0.994  | LR: 0.001
Epoch  28 | train: 0.0600 | val: 0.0726 | acc: 97.72% | AUC: 0.994  | LR: 0.001
Epoch  29 | train: 0.0490 | val: 0.0638 | acc: 97.87% | AUC: 0.994  | LR: 0.001
Epoch  30 | train: 0.0560 | val: 0.1084 | acc: 95.65% | AUC: 0.994  | LR: 0.001
Epoch  31 | train: 0.0643 | val: 0.1102 | acc: 95.77% | AUC: 0.995  | LR: 0.001
Epoch  32 | train: 0.0577 | val: 0.0973 | acc: 96.41% | AUC: 0.995  | LR: 0.001
Epoch  33 | train: 0.0456 | val: 0.0754 | acc: 97.41% | AUC: 0.995  | LR: 0.001
Epoch  34 | train: 0.0458 | val: 0.0748 | acc: 97.44% | AUC: 0.996  | LR: 0.001
Epoch  35 | train: 0.0410 | val: 0.0614 | acc: 98.33% | AUC: 0.995  | LR: 0.001
Epoch  36 | train: 0.0369 | val: 0.0686 | acc: 98.14% | AUC: 0.993  | LR: 0.001
Epoch  37 | train: 0.0362 | val: 0.0904 | acc: 97.08% | AUC: 0.995  | LR: 0.001
Epoch  38 | train: 0.0340 | val: 0.0924 | acc: 96.81% | AUC: 0.994  | LR: 0.001
Epoch  39 | train: 0.0414 | val: 0.0656 | acc: 97.78% | AUC: 0.996  | LR: 0.001
Epoch  40 | train: 0.0388 | val: 0.0525 | acc: 98.78% | AUC: 0.996  | LR: 0.001
Early stopping efter 41 epoker.
Klar!
Totalt antal utan m-komponent i K-fold poolen: 18848
Totalt antal med m-komponent i K-fold poolen: 2692
Total parameters: 172,322
--- Startar 10-Fold Cross Validation ---

========================================
 FOLD 1/10
========================================
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch   0 | train: 0.5426 | val: 0.4596 | acc: 92.80% | AUC: 0.908  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch   1 | train: 0.3220 | val: 0.2636 | acc: 95.77% | AUC: 0.966  | LR: 0.001
Epoch   2 | train: 0.2425 | val: 0.2132 | acc: 95.22% | AUC: 0.965  | LR: 0.001
Epoch   3 | train: 0.2712 | val: 0.2395 | acc: 95.77% | AUC: 0.963  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch   4 | train: 0.2198 | val: 0.2989 | acc: 96.61% | AUC: 0.968  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch   5 | train: 0.1815 | val: 0.2091 | acc: 93.22% | AUC: 0.972  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch   6 | train: 0.1702 | val: 0.2002 | acc: 97.40% | AUC: 0.985  | LR: 0.001
Epoch   7 | train: 0.1519 | val: 0.1690 | acc: 97.12% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch   8 | train: 0.1525 | val: 0.1522 | acc: 96.19% | AUC: 0.987  | LR: 0.001
Epoch   9 | train: 0.1353 | val: 0.2588 | acc: 87.46% | AUC: 0.980  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch  10 | train: 0.1274 | val: 0.1475 | acc: 97.40% | AUC: 0.989  | LR: 0.001
Epoch  11 | train: 0.1185 | val: 0.1475 | acc: 96.61% | AUC: 0.987  | LR: 0.001
Epoch  12 | train: 0.1364 | val: 0.2616 | acc: 86.95% | AUC: 0.974  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch  13 | train: 0.1125 | val: 0.1329 | acc: 96.52% | AUC: 0.991  | LR: 0.001
Epoch  14 | train: 0.1116 | val: 0.1365 | acc: 97.35% | AUC: 0.990  | LR: 0.001
Epoch  15 | train: 0.0962 | val: 0.1357 | acc: 96.28% | AUC: 0.990  | LR: 0.001
Epoch  16 | train: 0.1109 | val: 0.1703 | acc: 97.63% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch  17 | train: 0.0931 | val: 0.1283 | acc: 97.35% | AUC: 0.991  | LR: 0.001
Epoch  18 | train: 0.0889 | val: 0.1275 | acc: 97.45% | AUC: 0.990  | LR: 0.001
Epoch  19 | train: 0.0923 | val: 0.1409 | acc: 97.68% | AUC: 0.989  | LR: 0.001
Epoch  20 | train: 0.0943 | val: 0.1507 | acc: 97.21% | AUC: 0.990  | LR: 0.001
Epoch  21 | train: 0.0822 | val: 0.1357 | acc: 97.91% | AUC: 0.989  | LR: 0.001
Epoch  22 | train: 0.0775 | val: 0.1311 | acc: 96.61% | AUC: 0.990  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch  23 | train: 0.0790 | val: 0.1263 | acc: 97.45% | AUC: 0.991  | LR: 0.001
Epoch  24 | train: 0.0792 | val: 0.1435 | acc: 97.86% | AUC: 0.989  | LR: 0.001
Epoch  25 | train: 0.0749 | val: 0.1303 | acc: 97.45% | AUC: 0.990  | LR: 0.001
Epoch  26 | train: 0.0781 | val: 0.1415 | acc: 97.31% | AUC: 0.990  | LR: 0.001
Epoch  27 | train: 0.0722 | val: 0.1437 | acc: 97.91% | AUC: 0.990  | LR: 0.001
Epoch  28 | train: 0.0691 | val: 0.1683 | acc: 97.54% | AUC: 0.989  | LR: 0.001
Epoch  29 | train: 0.0609 | val: 0.1504 | acc: 95.22% | AUC: 0.990  | LR: 0.001
Epoch  30 | train: 0.0675 | val: 0.1462 | acc: 97.58% | AUC: 0.989  | LR: 0.001
Epoch  31 | train: 0.0650 | val: 0.1603 | acc: 96.84% | AUC: 0.987  | LR: 0.001
Epoch  32 | train: 0.0609 | val: 0.1367 | acc: 97.49% | AUC: 0.990  | LR: 0.001
Epoch  33 | train: 0.0577 | val: 0.1428 | acc: 95.12% | AUC: 0.991  | LR: 0.001
Epoch  34 | train: 0.0627 | val: 0.1284 | acc: 97.26% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold1.pth
Epoch  35 | train: 0.0530 | val: 0.1404 | acc: 97.26% | AUC: 0.991  | LR: 0.001
Epoch  36 | train: 0.0545 | val: 0.2115 | acc: 97.96% | AUC: 0.989  | LR: 0.001
Epoch  37 | train: 0.0483 | val: 0.1498 | acc: 97.86% | AUC: 0.990  | LR: 0.001
Epoch  38 | train: 0.0502 | val: 0.1608 | acc: 98.00% | AUC: 0.990  | LR: 0.001
Early stopping efter 39 epoker.
Klar!

Utvärderar bästa modellen för Fold 1...
-> Slutresultat Fold 1: Train Loss: 0.0450 | Val Loss: 0.1404 | AUC: 0.9912

========================================
 FOLD 2/10
========================================
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold2.pth
Epoch   0 | train: 0.5082 | val: 0.3905 | acc: 94.24% | AUC: 0.912  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold2.pth
Epoch   1 | train: 0.3109 | val: 0.2187 | acc: 96.52% | AUC: 0.972  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold2.pth
Epoch   2 | train: 0.2333 | val: 0.1790 | acc: 97.40% | AUC: 0.983  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold2.pth
Epoch   3 | train: 0.1903 | val: 0.1688 | acc: 94.80% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold2.pth
Epoch   4 | train: 0.1825 | val: 0.1340 | acc: 96.05% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold2.pth
Epoch   5 | train: 0.1728 | val: 0.1871 | acc: 91.88% | AUC: 0.990  | LR: 0.001
Epoch   6 | train: 0.1513 | val: 0.1178 | acc: 96.84% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold2.pth
Epoch   7 | train: 0.1350 | val: 0.1013 | acc: 97.77% | AUC: 0.992  | LR: 0.001
Epoch   8 | train: 0.1275 | val: 0.1231 | acc: 95.91% | AUC: 0.990  | LR: 0.001
Epoch   9 | train: 0.1208 | val: 0.1301 | acc: 95.22% | AUC: 0.988  | LR: 0.001
Epoch  10 | train: 0.1279 | val: 0.1006 | acc: 97.45% | AUC: 0.990  | LR: 0.001
Epoch  11 | train: 0.1121 | val: 0.1108 | acc: 97.82% | AUC: 0.990  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold2.pth
Epoch  12 | train: 0.1102 | val: 0.1032 | acc: 97.77% | AUC: 0.992  | LR: 0.001
Epoch  13 | train: 0.1069 | val: 0.0975 | acc: 97.86% | AUC: 0.992  | LR: 0.001
Epoch  14 | train: 0.1017 | val: 0.0996 | acc: 97.21% | AUC: 0.991  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold2.pth
Epoch  15 | train: 0.0972 | val: 0.0989 | acc: 97.35% | AUC: 0.993  | LR: 0.001
Epoch  16 | train: 0.0894 | val: 0.1115 | acc: 98.19% | AUC: 0.992  | LR: 0.001
Epoch  17 | train: 0.0947 | val: 0.0997 | acc: 97.35% | AUC: 0.990  | LR: 0.001
Epoch  18 | train: 0.0899 | val: 0.1157 | acc: 98.00% | AUC: 0.992  | LR: 0.001
Epoch  19 | train: 0.0830 | val: 0.1012 | acc: 97.63% | AUC: 0.990  | LR: 0.001
Epoch  20 | train: 0.0868 | val: 0.1018 | acc: 97.45% | AUC: 0.991  | LR: 0.001
Epoch  21 | train: 0.0780 | val: 0.1091 | acc: 97.26% | AUC: 0.990  | LR: 0.001
Epoch  22 | train: 0.0721 | val: 0.1165 | acc: 97.96% | AUC: 0.990  | LR: 0.001
Epoch  23 | train: 0.0696 | val: 0.1093 | acc: 95.96% | AUC: 0.992  | LR: 0.001
Epoch  24 | train: 0.0717 | val: 0.1069 | acc: 96.89% | AUC: 0.990  | LR: 0.001
Epoch  25 | train: 0.0618 | val: 0.1066 | acc: 97.73% | AUC: 0.991  | LR: 0.001
Epoch  26 | train: 0.0700 | val: 0.1261 | acc: 98.33% | AUC: 0.990  | LR: 0.001
Epoch  27 | train: 0.0694 | val: 0.1132 | acc: 97.45% | AUC: 0.988  | LR: 0.001
Epoch  28 | train: 0.0571 | val: 0.1193 | acc: 98.10% | AUC: 0.990  | LR: 0.001
Early stopping efter 29 epoker.
Klar!

Utvärderar bästa modellen för Fold 2...
-> Slutresultat Fold 2: Train Loss: 0.0807 | Val Loss: 0.0989 | AUC: 0.9925

========================================
 FOLD 3/10
========================================
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch   0 | train: 0.5315 | val: 0.5388 | acc: 92.34% | AUC: 0.894  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch   1 | train: 0.2945 | val: 0.2665 | acc: 96.01% | AUC: 0.964  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch   2 | train: 0.2200 | val: 0.2526 | acc: 96.70% | AUC: 0.972  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch   3 | train: 0.2030 | val: 0.1999 | acc: 95.82% | AUC: 0.974  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch   4 | train: 0.1896 | val: 0.1880 | acc: 94.85% | AUC: 0.978  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch   5 | train: 0.1616 | val: 0.2274 | acc: 96.98% | AUC: 0.981  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch   6 | train: 0.1618 | val: 0.1827 | acc: 97.03% | AUC: 0.981  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch   7 | train: 0.1442 | val: 0.1572 | acc: 97.08% | AUC: 0.984  | LR: 0.001
Epoch   8 | train: 0.1358 | val: 0.1511 | acc: 95.96% | AUC: 0.982  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch   9 | train: 0.1468 | val: 0.1576 | acc: 95.40% | AUC: 0.984  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch  10 | train: 0.1230 | val: 0.1522 | acc: 95.36% | AUC: 0.986  | LR: 0.001
Epoch  11 | train: 0.1235 | val: 0.1795 | acc: 97.08% | AUC: 0.983  | LR: 0.001
Epoch  12 | train: 0.1107 | val: 0.1977 | acc: 90.67% | AUC: 0.984  | LR: 0.001
Epoch  13 | train: 0.1022 | val: 0.1470 | acc: 96.70% | AUC: 0.985  | LR: 0.001
Epoch  14 | train: 0.0984 | val: 0.2456 | acc: 85.75% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch  15 | train: 0.0945 | val: 0.1619 | acc: 97.17% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch  16 | train: 0.0876 | val: 0.1434 | acc: 96.84% | AUC: 0.986  | LR: 0.001
Epoch  17 | train: 0.0921 | val: 0.1419 | acc: 96.70% | AUC: 0.985  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold3.pth
Epoch  18 | train: 0.0839 | val: 0.1388 | acc: 96.89% | AUC: 0.987  | LR: 0.001
Epoch  19 | train: 0.0827 | val: 0.1895 | acc: 97.59% | AUC: 0.984  | LR: 0.001
Epoch  20 | train: 0.0834 | val: 0.1726 | acc: 96.66% | AUC: 0.984  | LR: 0.001
Epoch  21 | train: 0.0798 | val: 0.1520 | acc: 96.66% | AUC: 0.984  | LR: 0.001
Epoch  22 | train: 0.0768 | val: 0.1522 | acc: 96.84% | AUC: 0.985  | LR: 0.001
Epoch  23 | train: 0.0716 | val: 0.1467 | acc: 96.70% | AUC: 0.986  | LR: 0.001
Epoch  24 | train: 0.0654 | val: 0.1791 | acc: 92.57% | AUC: 0.982  | LR: 0.001
Epoch  25 | train: 0.0725 | val: 0.1719 | acc: 97.31% | AUC: 0.984  | LR: 0.001
Epoch  26 | train: 0.0646 | val: 0.1619 | acc: 96.80% | AUC: 0.985  | LR: 0.001
Epoch  27 | train: 0.0690 | val: 0.2430 | acc: 97.35% | AUC: 0.984  | LR: 0.001
Epoch  28 | train: 0.0650 | val: 0.2027 | acc: 97.03% | AUC: 0.983  | LR: 0.001
Epoch  29 | train: 0.0605 | val: 0.1396 | acc: 96.33% | AUC: 0.984  | LR: 0.001
Epoch  30 | train: 0.0526 | val: 0.2185 | acc: 97.26% | AUC: 0.983  | LR: 0.001
Epoch  31 | train: 0.0598 | val: 0.1583 | acc: 95.78% | AUC: 0.983  | LR: 0.001
Epoch  32 | train: 0.0489 | val: 0.1861 | acc: 91.88% | AUC: 0.982  | LR: 0.001
Epoch  33 | train: 0.0488 | val: 0.2080 | acc: 97.45% | AUC: 0.984  | LR: 0.001
Early stopping efter 34 epoker.
Klar!

Utvärderar bästa modellen för Fold 3...
-> Slutresultat Fold 3: Train Loss: 0.0699 | Val Loss: 0.1388 | AUC: 0.9872

========================================
 FOLD 4/10
========================================
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch   0 | train: 0.5151 | val: 0.4801 | acc: 93.16% | AUC: 0.915  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch   1 | train: 0.3035 | val: 0.2704 | acc: 95.44% | AUC: 0.958  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch   2 | train: 0.2277 | val: 0.2328 | acc: 93.53% | AUC: 0.969  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch   3 | train: 0.1967 | val: 0.2042 | acc: 96.19% | AUC: 0.977  | LR: 0.001
Epoch   4 | train: 0.1670 | val: 0.2050 | acc: 93.95% | AUC: 0.972  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch   5 | train: 0.1810 | val: 0.2026 | acc: 96.70% | AUC: 0.979  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch   6 | train: 0.1473 | val: 0.1752 | acc: 96.88% | AUC: 0.984  | LR: 0.001
Epoch   7 | train: 0.1591 | val: 0.1784 | acc: 97.02% | AUC: 0.982  | LR: 0.001
Epoch   8 | train: 0.1281 | val: 0.1744 | acc: 97.53% | AUC: 0.983  | LR: 0.001
Epoch   9 | train: 0.1144 | val: 0.1550 | acc: 96.74% | AUC: 0.983  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch  10 | train: 0.1102 | val: 0.1696 | acc: 97.53% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch  11 | train: 0.1050 | val: 0.1518 | acc: 96.56% | AUC: 0.987  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch  12 | train: 0.0979 | val: 0.1706 | acc: 98.05% | AUC: 0.988  | LR: 0.001
Epoch  13 | train: 0.1020 | val: 0.1792 | acc: 96.42% | AUC: 0.978  | LR: 0.001
Epoch  14 | train: 0.1023 | val: 0.1747 | acc: 98.00% | AUC: 0.988  | LR: 0.001
Epoch  15 | train: 0.0856 | val: 0.1457 | acc: 97.16% | AUC: 0.988  | LR: 0.001
Epoch  16 | train: 0.0856 | val: 0.1496 | acc: 97.49% | AUC: 0.984  | LR: 0.001
Epoch  17 | train: 0.0838 | val: 0.1611 | acc: 98.00% | AUC: 0.988  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch  18 | train: 0.0760 | val: 0.1735 | acc: 98.05% | AUC: 0.989  | LR: 0.001
Epoch  19 | train: 0.0860 | val: 0.1410 | acc: 97.02% | AUC: 0.987  | LR: 0.001
Epoch  20 | train: 0.1048 | val: 0.1478 | acc: 96.19% | AUC: 0.986  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch  21 | train: 0.0750 | val: 0.1638 | acc: 97.86% | AUC: 0.989  | LR: 0.001
Epoch  22 | train: 0.0691 | val: 0.1770 | acc: 98.00% | AUC: 0.986  | LR: 0.001
Epoch  23 | train: 0.0677 | val: 0.1525 | acc: 97.58% | AUC: 0.987  | LR: 0.001
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold4.pth
Epoch  24 | train: 0.0677 | val: 0.1477 | acc: 96.84% | AUC: 0.989  | LR: 0.001
Epoch  25 | train: 0.0544 | val: 0.1618 | acc: 97.40% | AUC: 0.987  | LR: 0.001
Epoch  26 | train: 0.0579 | val: 0.1933 | acc: 97.86% | AUC: 0.985  | LR: 0.001
Epoch  27 | train: 0.0598 | val: 0.1602 | acc: 97.35% | AUC: 0.986  | LR: 0.001
Epoch  28 | train: 0.0533 | val: 0.1881 | acc: 93.21% | AUC: 0.982  | LR: 0.001
Epoch  29 | train: 0.0553 | val: 0.1802 | acc: 97.72% | AUC: 0.983  | LR: 0.001
Epoch  30 | train: 0.0485 | val: 0.1808 | acc: 97.49% | AUC: 0.985  | LR: 0.001
Epoch  31 | train: 0.0432 | val: 0.1959 | acc: 97.16% | AUC: 0.983  | LR: 0.001
Epoch  32 | train: 0.0403 | val: 0.1900 | acc: 97.67% | AUC: 0.985  | LR: 0.001
Epoch  33 | train: 0.0411 | val: 0.1980 | acc: 97.35% | AUC: 0.983  | LR: 0.001
Epoch  34 | train: 0.0426 | val: 0.1866 | acc: 96.14% | AUC: 0.981  | LR: 0.001
Early stopping efter 35 epoker.
Klar!

Utvärderar bästa modellen för Fold 4...
-> Slutresultat Fold 4: Train Loss: 0.0536 | Val Loss: 0.1477 | AUC: 0.9887

========================================
 FOLD 5/10
========================================
  -> ny bästa modell sparad till ../models/cnn_batchnorm_and_local_pool_fold5.pth
Epoch   0 | train: 0.5386 | val: 0.4535 | acc: 93.04% | AUC: 0.906  | LR: 0.001

,fold,train_loss,val_loss,val_accuracy,val_auc,val_spec,val_sens,tn,fp,fn,tp
0,1,0.044997,0.140434,97.259638,0.991165,0.977695,0.937037,1841,42,17,253
1,2,0.080701,0.098901,97.353760,0.992514,0.978769,0.937037,1844,40,17,253
2,3,0.069863,0.138811,96.889508,0.987225,0.976127,0.918216,1840,45,22,247
3,4,0.053628,0.147692,96.837209,0.988713,0.971292,0.947955,1827,54,14,255
4,5,0.049181,0.114955,97.632312,0.992082,0.980371,0.947955,1848,37,14,255
5,6,0.061636,0.102457,97.724106,0.991697,0.981423,0.947955,1849,35,14,255
6,7,0.092513,0.105932,97.721990,0.990783,0.983528,0.933086,1851,31,18,251
7,8,0.059190,0.157045,96.471681,0.985771,0.970292,0.925651,1829,56,20,249
8,9,0.102520,0.185383,95.264624,0.982069,0.953316,0.947955,1797,88,14,255
9,10,0.234930,0.250878,95.218199,0.987988,0.950133,0.966543,1791,94,9,260